### ISSUE TITLE
Python binding for Starspace

### ISSUE THREAD

**Issue by gitathrun** [facebookresearch/StarSpace#101]
Truely interesting embedding model, but I am wandering any plan for its Python binding?

**Comment by ledw** [comment]
@gitathrun Thanks for the suggestion! Agree that Python binding would be very useful. We currently have quite a few feature requests, so it might take some time for us to get to the Python binding, but it is on the list.

**Comment by mcganiz** [comment]
looking forward to see Python bindings.

**Comment by XiaolinZHONG** [comment]
it's will be much better for us to use python

**Comment by vpolimenov** [comment]
StarSpace ❤️ Python

**Comment by ledw** [comment]
@valentin-pinkau Thanks for working on that! I will look into the PATENT issue to see if we can change that.

**Comment by bedapudi6788** [comment]
@valentin-pinkau If possible can you share your python wrapper? Also, I am open if you need any help on that. (I am experienced in Python but never wrote a wrapper).

**Comment by valentin-pinkau** [comment]
@ledw is there any movement regarding the patent issue?

**Comment by LopezGG** [comment]
A python module would be very helpful

**Comment by maximedb** [comment]
For anyone interested, I made a class to easily communicate with `query_predict` using Python.
[link](https://github.com/maximedb/star_space_prediction/blob/master/star_space_prediction/__init__.py)

**Comment by ledw** [comment]
@valentin-pinkau It might be hard to remove the patent part as it is one of the standards for projects under facebookresearch. We will work on than and keep you updated.

**Comment by ledw** [comment]
@maximedb awesome! Thanks for working on that.

**Comment by petrLorenc** [comment]
Extended @maximedb code - [link](https://github.com/petrLorenc/tutorials/blob/master/Embeddings/StarSpace/StarSpaceInterface.ipynb)
You can use it for `query_predict `, `embed_doc` and `query_nn`

**Comment by freakeinstein** [comment]
I have started writing one. Had to learn pybind11 for this. Now, a basic version is ready. I have submitted a pull request here: https://github.com/facebookresearch/StarSpace/pull/197

**Comment by TitovS** [comment]
@freakeinstein I've tried to build your version but got this error:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import starwrap as sw
ImportError: dlopen(/Users/sergejtitov/Documents/Actual/Humanteq/LibHQ/starspace/python/test/starwrap.so, 2): Library not loaded: libstarspace.so
  Referenced from: /Users/sergejtitov/Documents/Actual/Humanteq/LibHQ/starspace/python/test/starwrap.so
  Reason: image not found
```
I'm not very experienced in compiling apps so would appreciate any help!

System info:
MacOS 10.14.1
Python 3.7.0
cmake version 3.13.1
Conan version 1.10.0

**Comment by freakeinstein** [comment]
@TitovS Can you check if `starwrap.so` is present at `/Users/sergejtitov/Documents/Actual/Humanteq/LibHQ/starspace/python/test/`? If not, it is not building properly. Then look for any other errors before that.

**Comment by TitovS** [comment]
Thank you for the swift reply!

I've checked - starwrap.so  is definitely in `python/test/`. Also I've done clean build and had same issue. Build log in attachments.

[starspace build log.txt](https://github.com/facebookresearch/StarSpace/files/2652029/starspace.build.log.txt)

**Comment by freakeinstein** [comment]
Hi, @TitovS  I have tested it on Mac OSX now. Please set `DYLD_LIBRARY_PATH ` as `path to lib` directory and it will work.

**Comment by TitovS** [comment]
Thanks! I've solved this issue by copying `libstarspace.so` to test directory. But I've defining will try setting up `DYLD_LIBRARY_PATH`

**Comment by ledw** [comment]
@valentin-pinkau It took a while but we finally updated the license: now it is under MIT license.

**Comment by ledw** [comment]
Added in https://github.com/facebookresearch/StarSpace/pull/197
