### ISSUE TITLE
Multi-task learning examples

### ISSUE THREAD

**Issue by bananemure** [facebookresearch/StarSpace#103]
Hi @ledw ,

The paper mention that multi-task learning is doable.
How do we implement that? Is there any exemplar script on how to do that?

Thanks

**Comment by ledw** [comment]
@bananemure Thanks for asking! The multi-task part is not currently in the codebase yet, but I will add it shortly, and provide an example. I will update this when it is available.

**Comment by ledw** [comment]
@bananemure just updated with multi-task feature in https://github.com/facebookresearch/StarSpace/commit/57c6212e89be5789487fbb96e860f5193ecad7fc.

To use that, simply put 
```
    -trainWord true \
    -wordWeight 0.2 
```

In your script. It will train word level examples together with the other task. The wordWeight controls the weight of word examples.

**Comment by bananemure** [comment]
@ledw Thanks very much.

**Comment by qiuwei** [comment]
@ledw is it possible to multitask with other different tasks?
For example, is it possible to mix a text classification task and a KB competition task?
