### ISSUE TITLE
Non-descriptive error message for trainMode=0 with a trainFile containing zero labels

### ISSUE THREAD

**Issue by vincentmajor** [facebookresearch/StarSpace#108]
I've noticed that when you try to train StarSpace with `trainMode = 0` on a (FastText formatted) `trainFile` that contains zero labels, the error message is of the form:
```
ERROR: File 'train.txt' is empty.
```
The file isn't actually empty (if it was, an exception would be thrown earlier and look like: "ERROR: Empty file.") and StarSpace knows that because it still prints out the number of words read in the dictionary:
```
Number of words in dictionary:  6
Number of labels in dictionary: 0
```
I suggest the error in `src/data.cpp`  at [line 65](https://github.com/facebookresearch/StarSpace/blob/master/src/data.cpp#L65) should be updated to something of the form:
```
ERROR: File 'train.txt' contains zero labels. Try trainMode = 5 or changing the -label argument.
```

Thanks!

Example:
```
echo "this is an example sentence" > ex_unlabeled.txt
echo "this is another sentence" >> ex_unlabeled.txt

./starspace train -trainMode 0 -trainFile ex_unlabeled.txt -model ex_unlabeled_model
```
Output:
```
Arguments: 
...
trainMode: 0
fileFormat: fastText
...
Start to initialize starspace model.
Build dict from input file : ex_unlabeled.txt
Read 0M words
Number of words in dictionary:  6
Number of labels in dictionary: 0
Loading data from file : ex_unlabeled.txt
Total number of examples loaded : 0
ERROR: File 'ex_unlabeled.txt' is empty.
```

**Comment by ledw** [comment]
@vincentmajor Thanks for the suggestion. Yes the error message you suggested is more accurate. We'll update that.

**Comment by jaseweston** [comment]
As I understand this was fixed here:
https://github.com/facebookresearch/StarSpace/pull/113
right @ledw  ?
