### ISSUE TITLE
What happens with unlabeled documents with trainMode=0?

### ISSUE THREAD

**Issue by vincentmajor** [facebookresearch/StarSpace#109]
The README for `trainMode=0` states "Each example contains both input and labels." But, StarSpace executes perfectly for a mixed case where some documents are labeled and others are not.
 
Example with `trainMode=0`:
```
echo "__label__1 this is a labeled test sentence" > ex_mixed.txt
echo "__label__0 a second labeled example" >> ex_mixed.txt
echo "this is an example sentence" >> ex_mixed.txt
echo "this is another sentence" >> ex_mixed.txt
 
./starspace train -trainMode 0 -trainFile ex_mixed.txt -model ex_mixed_model_0
```
Output:
```
Arguments: 
...
trainMode: 0
...
Start to initialize starspace model.
Build dict from input file : ex_mixed.txt
Read 0M words
Number of words in dictionary:  10
Number of labels in dictionary: 2
Loading data from file : ex_mixed.txt
Total number of examples loaded : 2
Training epoch 0: 0.01 0.002
...
Saving model to file : ex_mixed_model_0
Saving model in tsv format : ex_mixed_model_0.tsv
```
i.e. it works.
Similarly, with `trainMode=5`:
```
./starspace train -trainMode 5 -trainFile ex_mixed.txt -model ex_mixed_model_5
```
Output:
```
Arguments: 
...
trainMode: 5
...
Start to initialize starspace model.
Build dict from input file : ex_mixed.txt
Read 0M words
Number of words in dictionary:  10
Number of labels in dictionary: 2
Loading data from file : ex_mixed.txt
Total number of examples loaded : 4
Training epoch 0: 0.01 0.002
...
Saving model to file : ex_mixed_model_5
Saving model in tsv format : ex_mixed_model_5.tsv
```
Again, it works.
The dictionaries are identical (suggesting that despite `Total number of examples loaded : 2`, the first `trainMode=0` case is not throwing out the unlabeled documents) but the vectors are different. So, what is going on? How does StarSpace treat these unlabeled documents?
 
I suggest that the README be updated to note that:
- Training with `trainMode=0` does not require every document to have a label.
  - (But, there must be at least two labels.)
  - The unlabeled documents are treated ___.

This example also shows that training with `trainMode=5` on a file containing labeled documents, treats each label as a word/token in the dictionary and learns their embeddings. Perhaps a warning in the README/code for this case is warranted too?

**Comment by ledw** [comment]
@vincentmajor Thanks. In trainMode 0, it drops any example that do not contain a label. In your example, only the first two are considered as training examples. In trainMode 5, labels are not trained: only words in the examples are trained by their surrounding words.

**Comment by vincentmajor** [comment]
I'm still confused. In these two examples the vocabularies are identical.
```
awk '{print $1}' ex_mixed_model_5.tsv
awk '{print $1}' ex_mixed_model_0.tsv
```
Both output:
```
sentence
this
is
a
labeled
example
another
second
test
an
__label__0
__label__1
```
- For trainMode 0, if the examples without a label are dropped, why are words unique to those examples still in the vocab/embeddings? (e.g. 'labeled')
- For trainMode 5, the labels are within the vocab/embeddings, are they treated as any other word rather than a label? Would it make sense to drop the labels completely as the word order across the labels no longer means anything? (i.e. labels at the beginning or end of the line).

**Comment by ledw** [comment]
@vincentmajor The dictionary is built beforehand, so the words in dropped examples are still in the dictionary. Agree that it is not ideal, but not a huge problem. For trainMode 5, labels are ignored at training time.

**Comment by jaseweston** [comment]
closing this, as seems resolved
