### ISSUE TITLE
can you provide an example  of document ranking for unsupervised data?

### ISSUE THREAD

**Issue by tiru1930** [facebookresearch/StarSpace#114]
I have bunch of pdf's from which i can extract the text data and convert into documents where each document can have 3 to 5 sentences  . Now i want to use starspace for ranking these  documents for user queries. 

How can i use this unsupervised data in starspace for my use case? Correct me if my understanding is wrong on this usage of starspace.

**Comment by jaseweston** [comment]
Yes, you need the "ArticleSpace: Learning Sentence and Article Embeddings" section of the README, which describes the setting and provides an example script: 
https://github.com/facebookresearch/StarSpace/blob/master/README.md

**Comment by tiru1930** [comment]
Thank you , can you  tell ,how can i  test the same , like an API where user inputs query , starspace should return top 3 rank documents

**Comment by tiru1930** [comment]
Please check: is the file empty? Do the examples contain proper feature and label according to the trainMode? If your examples are unlabeled, try to set trainMode=5. , 

i got this error , when i had trained with trainMode 2 , my train data has ,each line is one document where sentence are separated by tab

**Comment by ledw** [comment]
@tiru1930 can you provide some examples of your file? Did you set -fileFormat 'labelDoc' ? Thanks.

**Comment by jaseweston** [comment]
Also for this question: "Thank you , can you tell ,how can i test the same , like an API where user inputs query , starspace should return top 3 rank documents" -- you can use the utility "query_predict" described in the README for this use case

**Comment by tiru1930** [comment]
able to train the model after adding -fileFormat 'labelDoc'

**Comment by jaseweston** [comment]
cool, so we'll close this then!
