### ISSUE TITLE
MultiRelationExample not working

### ISSUE THREAD

**Issue by Jingo91** [facebookresearch/StarSpace#117]
I guess it is used a wrong trainMode, a wrong fileFormat and missing baseDoc.
After changing trainMode to 4 and fileFormat to labelDoc it trained, but i couldnt test it, because i didnt specify a baseDoc:

Must provide base labels when label is featured.

**Comment by ledw** [comment]
@Jingo91 Hi, yes in labelDoc mode, since label is featured, you need to provide a list of featured labels in test mode. 
You can find examples of baseDoc in, e.g. https://github.com/facebookresearch/StarSpace/blob/master/examples/wikipedia_sentence_matching.sh
