### ISSUE TITLE
Any plans on making an R wrapper

### ISSUE THREAD

**Issue by jwijffels** [facebookresearch/StarSpace#118]
Are there any plans to make an R package around StarSpace?
Otherwise I don't mind making a stab at building one.

**Comment by jaseweston** [comment]
go for it!

**Comment by jwijffels** [comment]
I'm testing this out to see if at least compilation will work on different platforms before I do detailed R development. 
I've put the code in an R package to start to check if it builds. That worked on Linux however complaining that -std=gnu++11 is not a portable flag. Can this be made portable?

Next I was trying on Windows.  I've got boost headers 1.64 in C:/Users/Jan/Documents/R/win-library/3.4/BH/include. However when compiling I receive the following error. Do you have any advise on building this on Windows.

```
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -pthread -I"C:/Users/Jan/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/Jan/Documents/R/win-library/3.4/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c model.cpp -o model.o
In file included from model.cpp:10:0:
model.h: In static member function 'static void starspace::EmbedModel::check(const boost::numeric::ublas::matrix<float, boost::numeric::ublas::basic_row_major<>, boost::numeric::ublas::unbounded_array<float, std::allocator<float> > >&)':
model.h:187:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < m.size1(); i++) {
                       ^


```

**Comment by pommedeterresautee** [comment]
@jwijffels for C++ 11, is `CXX_STD = CXX11` not enough in Makevars?

**Comment by jwijffels** [comment]
@pommedeterresautee that's exactly what I did but CXX_STD = CXX11 in Makevars but on Linux that was not enough, I had to indicate to use -std=gnu++11
On Windows that also wasn't enough. The error seems to come from Boost when compiling it says: 
`c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.2/include" -DNDEBUG -pthread -I"C:/Users/Jan/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/Jan/Documents/R/win-library/3.4/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c model.cpp -o model.o`
So the R package picked up the location of Boost as it mentions  -I"C:/Users/Jan/Documents/R/win-library/3.4/BH/include" also the compiler is g++ with -std=gnu++11 as indicated also at https://github.com/facebookresearch/StarSpace/blob/master/makefile but apparenly still fails 
Any advise on building on Windows @jaseweston ?

**Comment by jwijffels** [comment]
FYI. This is a screenshot when trying to install the library on Windows. There seem to be issues regarding compilation of the software using MinGW compiler. E.g. the following code can not be compiled using MinGW (which is the default R compiler for Windows) as it is .
`auto numThreads = sysconf(_SC_NPROCESSORS_ONLN);`
![knipsel](https://user-images.githubusercontent.com/1710810/35882761-81d2b350-0b85-11e8-85f0-5ca8cd1540c0.PNG)
I think some efforts will have to be done by the StarSpace authors to make this compileable on Windows before an R package which will work cross-platform can be built.

**Comment by ledw** [comment]
@jwijffels Thanks for working on this. Is the warning in boost preventing you from compiling it? If so, can you try download boost 1.63 and see if that works?
For the error on sysconf it seems that it is not supported by MinGW. I'll look into how to fix that.

**Comment by jwijffels** [comment]
@ledw It's the elements which are non-compatible with the MinGW compiler which don't allow to compile this on Windows

**Comment by pommedeterresautee** [comment]
@jwijffels does it make sense to make a first version for Linux only?

**Comment by jwijffels** [comment]
That can of course make sense, but I would prefer to devote my time on building something portable.

**Comment by jwijffels** [comment]
@pommedeterresautee As StarSpace now compiles on Windows (with pull request https://github.com/facebookresearch/StarSpace/pull/146), I've made an initial R package available at https://github.com/bnosac/ruimtehol. It currently does model training + doc vectors. I'm planning to work on it this week. Feel free to provide remarks.

**Comment by jwijffels** [comment]
Closing this. R package is at https://github.com/bnosac/ruimtehol and allows to train a model, get embeddings, do the prediction and get nearest neighbours (apps query_predict/query_nn/print_ngrams/embed_doc). Anyone interested in trying it out and providing feedback would be highly appreciated. https://github.com/bnosac/ruimtehol
