### ISSUE TITLE
[Image Space] data train equals data test

### ISSUE THREAD

**Issue by YaYaB** [facebookresearch/StarSpace#120]
The data for train and test for Cifar10 are identical:
- https://s3.amazonaws.com/fair-data/starspace/cifar10-resnext.test
- https://s3.amazonaws.com/fair-data/starspace/cifar10-resnext.train

See: https://github.com/facebookresearch/StarSpace/blob/master/examples/image_feature_example_cifar10.sh

To reproduce:
```
wget -c "https://s3.amazonaws.com/fair-data/starspace/cifar10-resnext.train" -O "resnext.train"
wget -c "https://s3.amazonaws.com/fair-data/starspace/cifar10-resnext.train" -O "resnext.train"

diff resnext.train resnext.test
```
The diff outputs nothing

**Comment by ledw** [comment]
@YaYaB Thanks for reporting. We'll update that soon.

**Comment by ledw** [comment]
@YaYaB we updated the train file. Thanks again!
