### ISSUE TITLE
File format for trainMode 3

### ISSUE THREAD

**Issue by Tiriar** [facebookresearch/StarSpace#121]
Hello, I am trying to train sentence embeddings for sentence similarity task. I am trying to train it on the STS Benchmark dataset, which consists of sentence pairs, manually scored for sentence similarity.

As I understood from the wikipedia dataset you provide as example, the training data should consist of rows with sentences delimited by tabs. In accordance with this, I have preprocessed the sentences a bit, picked the ones with high similarity score and created a file with those sentence pairs delimited by \t. First 4 pairs as an example:

```
b'a plane is taking off .\tan air plane is taking off .\n'
b'a man is playing the cello .\ta man seated is playing the cello .\n'
b'some men are fighting .\ttwo men are fighting .\n'
b'a person is throwing a cat on to the ceiling .\ta person throws a cat on the ceiling .\n'
```

Unfortunately, when I try to start the training with this file, it throws an error saying that the file did not contain any valid examples. The whole output:

```
./starspace train -trainFile sts-train.txt -model starspace -trainMode 3

Arguments: 
lr: 0.01
dim: 10
epoch: 5
maxTrainTime: 8640000
saveEveryEpoch: 0
loss: hinge
margin: 0.05
similarity: cosine
maxNegSamples: 10
negSearchLimit: 50
thread: 10
minCount: 1
minCountLabel: 1
label: __label__
ngrams: 1
bucket: 2000000
adagrad: 1
trainMode: 3
fileFormat: fastText
normalizeText: 0
dropoutLHS: 0
dropoutRHS: 0
Start to initialize starspace model.
Build dict from input file : sts-train.txt
Read 0M words
Number of words in dictionary:  4340
Number of labels in dictionary: 0
Loading data from file : sts-train.txt
Total number of examples loaded : 0
ERROR: File 'sts-train.txt' does not contain any valid example.
```

Am I doing something wrong? Does it maybe need more than 2 sentences per line or something like that? Is the trainMode 3 suitable for this problem?

Thank you

**Comment by ledw** [comment]
@Tiriar you need to specify the fileFormat flag to labelDoc in order to train sentence as labels
`--fileFormat labelDoc`

Please try that and let me know if it works.

**Comment by Tiriar** [comment]
Thank you for the quick reply. Unfortunatelly I will not be able to try it in the next week, but I can let you know the week after. But yes, that was my mistake, I completely forgot about the labelDoc flag :). Thank you

**Comment by Tiriar** [comment]
So I tried training the model today with the fileFormat flag set to labelDoc. It works! Thank you, that was really a stupid mistake... Closing the issue.

**Comment by mattyd2** [comment]
@Tiriar Thank you for posting this question. 

Can you help me with a clarification question?

Do you know where it is documented that we need to provide the labelDoc format with spaces around punctuation?

`"I 'm ready to transfer , can I do another ? Can I do another t-balance ?"`

as opposed to:

`"I'm ready to transfer, can I do another? Can I do another t-balance?"`

Any guidance would be appreciated.

**Comment by Tiriar** [comment]
@mattyd2 I think the wikipedia sentences in the example for learning sentence embeddings were preprocessed this way (the example in examples/wikipedia_sentence_matching.sh).

Also most of the tokenizers I ever used add spaces in front of apostrophes and punctuation. I mostly now use the tweettokenizer from python nltk package. Many algorithms want to have the data preprocessed this way, I guess because it is then easier to just split the sentences by spaces and of course punctuation is a special token than you can often throw away altogether (unless you want the model to learn differences between declarations and questions, then the punctuation might be useful as a token).
