### ISSUE TITLE
MaxTrainTime exceeded and Segmentation fault in both train and test mode

### ISSUE THREAD

**Issue by ben0it8** [facebookresearch/StarSpace#124]
Lately, I noticed Segmentation fault when calling train/test. 
To see whether its a custom issue or not, I ran examples/classification_ag_news.sh, and interestingly enough, I got the following errors (of course, with the latest Starspace build using the default params as in the shell script):

- after the 3rd epoch, it gives :
> 'MaxTrainTime exceeded.'

- then it saves the model and gives:
> ./examples/classification_ag_news.sh: line 62:  1315 Segmentation fault      ./starspace train -trainFile "${DATADIR}"/ag_news.train
>  -model "${MODELDIR}"/ag_news -initRandSd 0.01 -adagrad false -ngrams 1 -lr 0.01 -epoch 5 -thread 20 -dim 10 -negSearchLimit 5 -maxN
> egSamples 3 -trainMode 0 -label "__label__" -similarity "dot" -verbose true

Similarly, in test mode it throws Segmentation fault as well. Did anyone notice similar issues?

Thanks,
Oliver

**Comment by ledw** [comment]
@ben0it8 Hi Oliver, thanks for reporting. I cannot reproduce the error using the current version and the examples/classification_ag_news.sh script. Could you try `make clean` first and `make` again to see if the error persist?

**Comment by ben0it8** [comment]
@ledw Thanks, make clean worked out!
