### ISSUE TITLE
How to send a query for prediction using curl

### ISSUE THREAD

**Issue by bedapudi6788** [facebookresearch/StarSpace#126]
Hi, is there anyway to create some API so that we can call from different languages. I have tried creating a wrapper for python but am getting some issues with linking as I am inexperienced in interfacing with c++ from python. Is there any way I can create some REST API service so that in query_predict in place of cin, we can use input from API. Any suggestions would be appreciated.

**Comment by ledw** [comment]
@bedapudi6788 Hi, sorry for the delay in replying. What is the issues you are experiencing? Would you mind to share your code? Thanks.

**Comment by davidalbertonogueira** [comment]
I will probably tackle the same problem in the future. @bedapudi6788 , have you solved it?

**Comment by bedapudi6788** [comment]
@davidalbertonogueira As my knowledge of c++ is minimal at best, I couldn't find anyway to host the model or write a python wrapper. So, I am currently using subprocess module in python to use my models, but it's not the best way to do this.

**Comment by ledw** [comment]
See python example in https://github.com/facebookresearch/StarSpace/issues/101

**Comment by NAZMULBABLU** [comment]
RIGHT  A MOMENT  GET A RIGHT  DECISION IT MUST CHANGE A BETTER THINGS
