### ISSUE TITLE
How to interpret evaluation metrics

### ISSUE THREAD

**Issue by jgiere** [facebookresearch/StarSpace#127]
Hi,
I train and test my data set successfully, but I don't understand how to interpret the evaluation metrics of my test data. I get the following results:

```
Evaluation metrics:
hit@1: 0.940667 hit@10: 1 hit@20: 1 hit@50: 1 mean ranks : 1.114 Total examples : 1500
```

How can I understand the "hit@*" and "mean ranks"?

Thank you for your help.

**Comment by ledw** [comment]
@jgiere Please see the discussions in the following issue:
https://github.com/facebookresearch/StarSpace/issues/81
