### ISSUE TITLE
Simple useWeight clarification

### ISSUE THREAD

**Issue by rainjacket** [facebookresearch/StarSpace#129]
I have a historical data set with these properties:
- each text has a sample weight, w
- each text has each label i with some probability, p_i, where sum_i{p} = 1

Which of the following inputs will have the expected behavior?
a) word_1:w word_2:w ... word_n:w label_1:p_1 label_2:p_2 ... label_n:p_n
b) word_1 word_2 ... word_n label_1:w·p_1 label_2:w·p_2 ... label_n:w·p_n

I'm not sure if one of the above is correct, or if they both / neither do what I want. Thanks for the advice! :)

**Comment by ledw** [comment]
@rainjacket to use sample weight in combination with word/label weight, you can use the following form:
__weight__:w word_1 word_2 ... label_1:p_1 label_2:p2 ... label_n:p_n
