### ISSUE TITLE
Please clarify terminology: labels, input, lhs, rhs

### ISSUE THREAD

**Issue by matthias-samwald** [facebookresearch/StarSpace#130]
I think one of the most confusing aspects in the documentation / command line interface is the terminology around 'label', 'input', 'LHS' and 'RHS', which are used interchangeably. 

Looking at the code at https://github.com/facebookresearch/StarSpace/blob/66a5d5b2165c9dfa25b7fa3a13561c686e75f1c9/src/doc_data.cpp , I assume that "LHS" is synonymous with "input", and "RHS" is synonymous with "label"?

Probably the documentation would be easier to understand if the terms would be less intermixed, e.g., "input" and "label" refer to the structure of the input document, and "LHS" and "RHS" refer to what is imputed to the starspace model. 

The documentation could then be made clearer, e.g.,

"Each example contains a collection of labels. At training time, one label from the collection is randomly picked as the label, and the rest of the labels in the collection become the input."

could become

"Each example contains a collection of labels. At training time, one label from the collection is randomly picked as the RHS, and the rest of the labels in the collection become the LHS."

**Comment by ledw** [comment]
@matthias-samwald thanks for the suggestion. That's very helpful.

**Comment by ledw** [comment]
Updated: https://github.com/facebookresearch/StarSpace/pull/133/commits/2e853883e4c2b0c8dd65eb332213e2123d9e4466
