### ISSUE TITLE
Training StarSpace using Mode 5 + Mode 3

### ISSUE THREAD

**Issue by mattyd2** [facebookresearch/StarSpace#131]
Hi,

In the [StarSpace paper](https://arxiv.org/pdf/1709.03856.pdf) one evaluation exercise was to check the performance of a StarSpace model trained (multi-tasked) on both word and sentence level. 

In the READ.ME it's unclear how to do this.

Do you have any guidance?

**Comment by ledw** [comment]
@mattyd2 you can use the flag `-trainWord true` and `-wordWeight` to specify the weight used for word level training examples. Updated README to reflect that.

**Comment by mattyd2** [comment]
@ledw thank you for the update. Is there any reference that provides more details about the impact word-level training examples have on the sentence representation when training in Mode 3?
