### ISSUE TITLE
Pagespace recommendation | slow inference

### ISSUE THREAD

**Issue by alsora** [facebookresearch/StarSpace#138]
Hi,

I am trying starspace for pagespace recommendation.

I trained a model on 200K users with approximately 30-50 items each.
`./starspace train 
  -trainFile ${TRAINFILE} 
  -model ${MODEL} 
  -initRandSd 0.01 
  -lr 0.01 
  -epoch 50 
  -thread 40 
  -dim 100 
  -maxNegSamples 120 
  -negSearchLimit 120 
  -trainMode 1 
  -label "L" 
  -verbose true`

The training went fine, but i'm facing some problems during the test phase: it is extremely slow!
I had to use a test file with only 5K users and it took almost 8 hours (almost double of the training time).

`./starspace test 
  -model ${MODEL} 
  -testFile ${TESTFILE} 
  -dim 100 
  -label "L" 
  -thread 40 
  -trainMode 1 
  -verbose true`

Is it normal or am I doing something wrong?
Is is possible to perform train and test using a GPU?

Thank you

**Comment by pommedeterresautee** [comment]
Why not put the vectors in Annoy and measure on it?

**Comment by jaseweston** [comment]
The speed at testing time should depend on how many unique items there are in the dictionary -- how many are there?
@ledw

**Comment by alsora** [comment]
The training dataset contains about 1 million unique items

**Comment by ledw** [comment]
@alsora yes, as @jaseweston mentioned, the test will use ALL items to measure the performance. In test time, we recommend to sample a random 1K or 10K items to compare with (where we call base items). You can specify the file that contains base items by the argument -basedoc (You need to generate the base items  file beforehand).

**Comment by ledw** [comment]
Closing since no updates.
