### ISSUE TITLE
Training GraphSpace with large data

### ISSUE THREAD

**Issue by tuphamngoc** [facebookresearch/StarSpace#139]
Dear all

I have 400K customers including relationship data. We're analysing them by the GraphSpace model.
I created a file graph-relationship including ~380M relationships (size 18GB) with format:
    user_1 friend __label__user2
	...
	
I got an issue over memory. I using CPU 16 cores with 64GB RAM, but it's not enough memory and the GraphSpace was killed.

Anyone have any solution for my problem?
How to optimize my data to decrease Hardware requirements? 

Which are server requirement enough for 380M data (or more..)? How to calculate?

**Comment by ledw** [comment]
@tuphamngoc Hi, it sounds like your data is too big to be loaded in to memory. You can roughly calculate the usage by 
`O(num_of_relations * size_of(int32 + float)) + O(size_of(float) * num_of(users + label_users) * dimension)`
What are the number of unique users and labels in your data? What is the dimension you're using?
One thing we can do is to write an another data loader that does not load the data into memory.

**Comment by ledw** [comment]
Similar issue: https://github.com/facebookresearch/StarSpace/issues/137
Closing this one now.
