### ISSUE TITLE
using reference labels for multi word labels at prediction time

### ISSUE THREAD

**Issue by paulgid** [facebookresearch/StarSpace#143]
I am trying to find out if there is a possibility at prediction time,  of having some sort of identifier returned as predictions instead of documents or multi-word labels. In the wikipedia search example (document search task, trainingMode 2), It would mean having a wikipedia article and a reference, say URL, in the basedoc, and the prediction returning the URLs instead of the documents.  That is if predicted document in the basedoc is as follows: 

`word1 word2 word3 ... wordn <tab>__label__URL`

Instead of getting `word1 word2 word3 ... wordn` as the prediction, I will get `__label__URL` instead. 

In my use case I generate the labels that end up in the basedoc after combining multiple sources. After all preprocessing it's is cumbersome to map back to original sources, but with a self defined `_label__X` I can achieve that. 

Is that possible? Is that a valid feature to have?

**Comment by ledw** [comment]
@paulgid, thanks for the feature request. I felt that is a more case specific feature. Please feel free to add that feature and submit a pull request. The prediction part is mostly contained in src/starspace.cpp (https://github.com/facebookresearch/StarSpace/blob/2016eaab37e529f85fa95e9b83fe85c424a21d2a/src/starspace.cpp#L253)
