### ISSUE TITLE
loading starSpace model

### ISSUE THREAD

**Issue by PrashantRanjan09** [facebookresearch/StarSpace#147]
I ran the command :
./starspace train -trainFile file.txt -model /destinationFolder/model_name -dim 300

I see two files. 
model_name
model_name.tsv

How do we load the model file(model_name) for starSpace.

**Comment by ledw** [comment]
@PrashantRanjan09 You can load either one of the output files: just use -`model model_name` (or `-model model_name.tsv`) in `./starspace test` and it should work.

**Comment by PrashantRanjan09** [comment]
@ledw  Thank you so much.

**Comment by PrashantRanjan09** [comment]
@ledw this works on the command line. But how do i load this model in a jupyter notebook.

**Comment by ledw** [comment]
@PrashantRanjan09 we currently don't have a python binding. However, you can write your own code to load the .tsv format model and play with it.

**Comment by PrashantRanjan09** [comment]
@ledw Thank you. Thats what i did.
