### ISSUE TITLE
embed_doc / query_predict receiving SIGABORT

### ISSUE THREAD

**Issue by ryaoi** [facebookresearch/StarSpace#150]
I was testing embed_doc and I ran into sigabort when i executed ` ./embed_doc ./model/tag_model` and then typed some text.

```
Start to load a trained starspace model.
STARSPACE-2017-2
Model loaded.
Input your sentence / document now:
Trying out embed_doc!
Trying out embed_doc!
Assertion failed: (pair.first < this->numRows()), function forward, file src/proj.h, line 57.
[1]    86893 abort      ./embed_doc tag_model
```

I wanted to know if I was using it the right way.
I also received sigabort when i was trying out `query_predict` with my model. Assert() also failed at the line 57 for the `query_predict` too.

**Comment by ledw** [comment]
@ryaoi Hi, it is the correct way to use the ./embed_doc file, however I'm not sure why you're seeing this (if the model is saved correctly it should work). It's a bit hard for me to debug without your model file. Can you try to see if the .tsv file works? or does it also give sigabort?

**Comment by ryaoi** [comment]
Hi @ledw, thanks for the reply.
I guess I am using the wrong model.
I compiled the module with
`./starspace train -trainFile input.txt -model tagspace -label '#'`.

My training sample looks like
```
#digital, Les conseils du CDO d’Axa France pour relever le défi du RGPD Le nouveau règlement européen visant à améliorer la protection des données personnelles entrera en vigueur le 25 mai prochain. Interview d ' Antoine Denoix CDO d ' Axa France.
#digital, Six questions sur les néo-banques : des services moins chers... vraiment révolutionnaires ? Avec des cartes gratuites offrant un très grand nombre de services les néo-banques intriguent et font parfois peur. On décrypte pour vous les avantages et inconvénients de  ces nouvelles venues qui secouent un secteur jusqu ' alors figé.
```

There is another model which i used to try out the `embed_doc` with another model which was compiled with 
```

```
and it works fine.

**Comment by ledw** [comment]
@ryaoi Thanks for sharing your input file! I tried to train a test model on the training examples you provided with '#' and the command you provided. The test model I saved works fine with the ./embed_doc query. 
Do you have any problems with it? Otherwise I'll close the task.

**Comment by ryaoi** [comment]
I guess it's better to dump the output.
```
./starspace train -trainFile ./dataset/tag.model -epoch 1 -model ./model/tag_model -label '#'
Read 12M words
Number of words in dictionary:  367819
Number of labels in dictionary: 4702
Epoch: 100.0%  lr: 0.000000  loss: 0.010515  eta: <1min   tot: 0h2m29s  (100.0%)Arguments:
lr: 0.01
dim: 100
epoch: 1
maxTrainTime: 8640000
saveEveryEpoch: 0
loss: hinge
margin: 0.05
similarity: cosine
maxNegSamples: 10
negSearchLimit: 50
thread: 10
minCount: 1
minCountLabel: 1
label: #
ngrams: 1
bucket: 2000000
adagrad: 1
trainMode: 0
fileFormat: fastText
normalizeText: 0
dropoutLHS: 0
dropoutRHS: 0
Start to initialize starspace model.
Build dict from input file : ./dataset/tag.model
Loading data from file : ./dataset/tag.model
Total number of examples loaded : 291317
Training epoch 0: 0.01 0.01

 ---+++                Epoch    0 Train error : 0.01038287 +++--- ☃
Saving model to file : ./model/tag_model
Saving model in tsv format : ./model/tag_model.tsv

R01s:getstarspace Ryotalejap$ ./embed_doc ./model/tag_model
Start to load a trained starspace model.
STARSPACE-2017-2
Model loaded.
Input your sentence / document now:
trying out the model!
trying out the model!
Assertion failed: (pair.first < this->numRows()), function forward, file src/proj.h, line 57.
Abort trap: 6
```
Maybe my training samples are corrupted. You can close this issue. I'm going to use another model.

**Comment by ledw** [comment]
@ryaoi you're welcome. Closing the issue for now.
