### ISSUE TITLE
Support for Asian Languages

### ISSUE THREAD

**Issue by shishircc** [facebookresearch/StarSpace#151]
Hi, 

Are Asian languages handled by the model ? 

I trained a classification model for Japanese text (tokenized and space delimited). The training was a bit odd with strange loss values which did not change much and pretty bad evaluation on test. I suspect that the model is not handling Japanese text well. 

Later when I try to use that trained model for prediction, the query_predict hangs after I enter the japanese text. 

![screen shot 2018-05-31 at 10 54 16 am](https://user-images.githubusercontent.com/7352186/40758673-1b34f668-64c1-11e8-8e19-1dafd0365862.png)
![screen shot 2018-05-31 at 10 57 04 am](https://user-images.githubusercontent.com/7352186/40758735-61b6a550-64c1-11e8-9910-0d4c3fff3b48.png)

**Comment by shishircc** [comment]
My training data looks like this ... I follow fasttext format...
`__label__X:1 __label__X:2 __label__X:3 __label__X:4 __label__X:5 __label__X:6 __label__X:7 __label__X:8 __label__X:9 __label__X:10 __label__X:11 __label__X:12 __label__X:13 __label__X:14 __label__X:15 __label__X:16 __label__X:17 __label__X:18 __label__X:19 __label__X:20 __label__X:21 __label__X:22 __label__X:23 __label__X:24 __label__X:25 ［ ２ ４ 日 　 ロイター ］   ＊ 米 複合 企業 スリーエム （ ３Ｍ ） > が 午前 の 取引 で ７ ． ３ ％ 安 の １ １ ９ ． ８ ４ ドル 。 少なくとも ７ カ月 ぶり の 安値 を 更新 。   ＊   第 １ ･ 四半期 決算 は 調整 後 の １ 株 利益 が ２ ． ５ ０ ドル と 、 トムソン ・ ロイター が まとめる た アナリスト 予想 と 一致 。   ＊ ただ ＲＢＣ キャピタル ･ マネジメント の アナリスト 、   ディーン ・ ド レイ 氏 は 、 減税 が 相殺 要因 に なる た と 指摘 。   ＊ ３Ｍ は 、 通年 の 調整 後 の １ 株 当たり 利益 見通し を １ ０ ． ２ ０ ─ １ ０ ． ５ ５ ドル と する 、 上限 を 従来 の １ ０ ． ７ ０ ドル から 下方 修正 。   ＊ 現地 通貨 建て の 本源 的 売上 高 （ オーガニックセールス ） の 伸び は ３ ─ ４ ％ に なる と 予想 。 従来 予想 は ３ ─ ５ ％ だ た 。   ＊ ＲＢＣ キャピタル の ド レイ 氏 は 、 通年 業績 見通し の 下方 修正 は 大幅 だ 修正 で は ない と する ながら も 、 かなり 早い 段階 で 修正 が 行う れる た こと で 影響 は 拡大 する と 指摘 。   ＊ 投資 判断 は アナリスト ５ 人 が 「 買い 」 以上 、 ６ 人 が 「 ホールド 」 、 ４ 人 が 「 売る 」 以下 。 トムソン ・ ロイター の データ に よる と 目標 株価 中央 値 は ２ ３ ０ ドル 。   ＊ 株価 は 年初 から 約 １ ４ ％ 下落 。 日本語 ニューストピックガイド ※ 原文 記事 など 関連 情報 は 画面 右側 に ある 「 関連 コンテンツ 」 メニュー から ご覧 くださる`

**Comment by ledw** [comment]
@shishircc Hi, StarSpace does not have special handling for Asian language. It splits the sentence by ' ' to get words in dictionary. 
Let me check on your specific examples and get back to you later.

**Comment by ledw** [comment]
Closing for now as we're unlikely to add specialized support for Japanese.
