### ISSUE TITLE
Recover embeddings for labels themselves in TagSpace model

### ISSUE THREAD

**Issue by rexdouglass** [facebookresearch/StarSpace#152]
First, thank you for a wonderful package.

I am fitting the TagSpace model. I believe I understand how to recover embeddings of the right hand side grams, and ngrams. I believe I can also recover the embedding of a full document.

I do not yet know if/how to recover the embedding of the labels. 

The instruction "Model: the mapping learnt goes from bags of words to bags of tags, by learning an embedding of both." suggests that in addition to projecting the words of the right hand side into their own space, the labels are themselves being projected into a space (either their own, or the same as the RHS?). Is this true, and if so, how do we retrieve those embedding? I have hundreds of thousands of labels, and I would be very interested to see how they are embedded relative to each other.

**Comment by rexdouglass** [comment]
I think I may have answered my own question: The label embeddings are found at the very bottom of the model tsv file? Is that correct?

**Comment by ledw** [comment]
@rexdouglass Yes, that is correct. Thanks for your comments! Let us know if you have any other questions. 
Closing the issue for now.
