### ISSUE TITLE
any example for DocSpace document recommendation

### ISSUE THREAD

**Issue by HuangZhanPeng** [facebookresearch/StarSpace#153]
does any example for DocSpace document recommendation, I find every except that

I form the input format like follow 

```
roger federer loses <tab> venus williams wins <tab> world series ended
i love cats <tab> funny lolcat links <tab> how to be a petsitter 
```

but it does not work

**Comment by ledw** [comment]
Hi @HuangZhanPeng, what do you mean by it does not work?
The examples in wikipedia is similar to DocSpace: for instance, if you change the trainMode from 3 to 1 in this: https://github.com/facebookresearch/StarSpace/blob/master/examples/wikipedia_sentence_matching.sh
It essentially becomes an example for DocSpace.

**Comment by HuangZhanPeng** [comment]
@ledw thanks a lot~
