### ISSUE TITLE
Explanation of `predictionFile` for `recomm_user_artists.sh`

### ISSUE THREAD

**Issue by bkj** [facebookresearch/StarSpace#154]
Can anyone explain the meaning of the `predictionFile` in the `recomm_user_artists.sh` example?
```
$ ./starspace test \
  -model ${MODELDIR}/${DATASET}/user_artists \
  -testFile ${DATADIR}/${DATASET}/user_artists.test \
  -dim 100 \
  -label "A" \
  -thread 40 \
  -trainMode 1 \
  -predictionFile preds \
  -K 10

$  head -n 20 preds
Example 0:
LHS:
A190 A199 A207 A217 A227 A228 A229 A291 A293 A298 A300 A316 A333 A344 A403 
A420 A464 A498 A538 A542 A546 A548 A679 A681 A683 A687 A691 A696 A704 A1047 
A1048 A1090 A1106 A1400 A1470 A1492 A1502 A1632 A1976 A2121 A2277 A2407 A2977 
A3373 A3400 A3461 A3730 A5978 A9079 
RHS: 
A1246 
Predictions: 
(--) [0.508832]	A546 
(--) [0.444638]	A3373 
(--) [0.440827]	A5978 
(--) [0.4389]	A1047 
(--) [0.432931]	A7787 
(--) [0.419802]	A1502 
(--) [0.401226]	A683 
(--) [0.397157]	A65 
(--) [0.39344]	A2977 
(--) [0.393277]	A4773 
```

It looks like most of the predictions are on the LHS of the model -- what does that mean?  

Thanks
Ben

**Comment by ledw** [comment]
Hi @bkj , the prediction predicts the K top answers for RHS. In the example of recomm_user_artists.sh, LHS is represented by the collection of artists (more, specifically, the embedding of LHS is the average of the item embeddings for items in LHS). Therefore, the item embedding could appear in predictions of RHS as it can be close to the LHS embedding.

**Comment by ledw** [comment]
@bkj Thanks for implementing the feature! Closing the task.
