### ISSUE TITLE
Gender Detection

### ISSUE THREAD

**Issue by beshoo** [facebookresearch/StarSpace#158]
Dea all , I have 1m Giving name , all is labeled Fasttext style , as i know that  StarSpace dealing with  Words 
So as long as the name is only one word !

I was told that fasttext is doing this : 

> Fasttext it just memorizes the number of males and females per name. If that's what you want then you should use Scikit or something and treat each name as an individual token

Please note that the names is identical , so there is no repeated names !  

Well i am looking for some way to do this via Neural Networks , by splitting the name to characters and feed character unicode number to the array then feed the "Neural Networks"!

Well i am not Neural Networks Expert but what i found here that StarSpace doing it work via Neural Networks, which is very nice if i can do this by StarSpace .

The goal is not to match database for giving name ! but search for a Brand new name and try to guess the gender.

And if we can do this with any language even Japanese since i have Japanese names.
Can this project don via StarSpace ?

Regards

**Comment by ledw** [comment]
@beshoo Hi, thanks for posting your question. I think you can try StarSpace for this problem, but should also try other classical methods in classification. Here you can generate your input features of a name by the character n-grams of in that name, and label is gender.

**Comment by ledw** [comment]
Closing old issue.
