### ISSUE TITLE
query_predict failing

### ISSUE THREAD

**Issue by firesting** [facebookresearch/StarSpace#159]
./query_predict /tmp/starspace/models/wikipedia_sentence_match.tsv k  /tmp/starspace/data/wikipedia_test_basedocs_tm3.txt 
Start to load a trained embedding model in tsv format.
Loading dict from model file : /tmp/starspace/models/wikipedia_sentence_match.tsv
Number of words in dictionary:  267523
Number of labels in dictionary: 0
Loading model from file /tmp/starspace/models/wikipedia_sentence_match.tsv
Model loaded.
Loading base docs from file : /tmp/starspace/data/wikipedia_test_basedocs_tm3.txt
Finished loading 10000 base docs.
Enter some text: 'hello'

Enter some text: 

There is no result of either labels/documents on trying to do query_predict with sentence model (from the example). Could any one help me understand why so ? and also help me understand the need for basedocs file ?

**Comment by ledw** [comment]
@firesting Thanks for reporting. I think you need to remove the '' from 'hello' when you input the text. In addition basedoc argument is not needed for ./query_predict I believe.

**Comment by ledw** [comment]
Closing the issue as there's no recent update.
