### ISSUE TITLE
Applying starspace for a weakly supervised ranking dataset

### ISSUE THREAD

**Issue by kretes** [facebookresearch/StarSpace#164]
Hello, I should have put that to a user group but my invitation is still pending, so I decided to start a ‘discussion’ here:

We would like to use starspace to train embeddings for a document ranking problem. Following the paper and starspace tool - it looks like a really promising technique! 

We have a dataset consisting of search queries and search results with indicator of a clicked document. What we would like to achieve is train embeddings in a way that the search query would be similar to the clicked document but not similar to other, non-clicked documents.

One additional detail here is that other non-clicked documents on the same search results page are very similar to the clicked one, while documents sampled from other search results would naturally be far away.

We didn’t find a way to directly use starspace trainModes to achieve that.
What we are currently doing is we are preparing a labelDoc file with a search query on the LHS and all the clicked documents on the RHS and training with trainMode 0.
```
<search query> <tab> <relevant doc 1> <tab> <relevant doc 2> …
```
The downside of that is that starspace is not provided with any ‘not-relevant’ documents at all.
Furthermore we would like to separate local and global negatives and e.g. sample from each of them separately.

Is there a way to use starspace for that case currently?
Is this something you consider valuable and would accept a contribution?

**Comment by pommedeterresautee** [comment]
Can the weight = 0 be used for that purpose?

**Comment by ledw** [comment]
@pommedeterresautee I think @kretes is asking whether we can use the provided non-clicked documents as negatives. In that case, there is no current way to do so. Using weight = 0 is essentially telling StarSpace to ignore these examples, which can be achieved by removing those examples in training.

**Comment by pommedeterresautee** [comment]
You are right, it should be a negative weight of -1 and Starspace should exclude these examples from negative examples (otherwise the negative weight would be positive...).

**Comment by imathur** [comment]
@kretes Were you able to solve this issue? What were the training modes you used and were the results satisfactory? I'm trying to solve a ranking problem myself so would love to hear how you used StarSpace for your use case.

**Comment by kretes** [comment]
@imathur We started off with using trainMode 0 and additionally we employed a modification similiar to this one: https://github.com/zwChan/StarSpace/commit/e3cf6a09c8be080f3455cf16a17441e553a39c18 by @zwChan 

Using this hard negatives strategy we didn't get a clear benefit though.

To sneak our other findings - we found the representations trained with starspace to be valueable overall. What we struggle the most is memory-efficiency of Starspace.

**Comment by ledw** [comment]
@kretes @zwChan The modified version looks cool! Would you be willing to submit a PR on it? We would like to integrate it to StarSpace codebase as it seems like a useful feature.
@kretes I'm interested to learn your struggle on the memory efficiency. Would you be able to share roughly the size of data you deal with and your use-case scenario? There are things we can do to improve memory efficiency.
