### ISSUE TITLE
How to use this library to recommend texts?

### ISSUE THREAD

**Issue by tiagodavi** [facebookresearch/StarSpace#165]
Hi Guys, I would like some help if it's possible. 

I saw an example like that to learn text content, but I didn't understand what that <tab> is.

`roger federer loses <tab> venus williams wins <tab> world series ended
i love cats <tab> funny lolcat links <tab> how to be a petsitter  `

Le'ts imagine that I have a document A and a document B. I would like to recommend the document B to the user that liked the document A if the document B is 80% similar to the document A. Is there an exemple of how to do that?

**Comment by ledw** [comment]
Hi @tiagodavi, yes you can use StarSpace for that. Please check out the wikipedia sentence match section in our paper and your use case is similar to that: https://arxiv.org/abs/1709.03856
Here's the example script: https://github.com/facebookresearch/StarSpace/blob/master/examples/wikipedia_sentence_matching.sh

**Comment by tiagodavi** [comment]
Thank you!

Em seg, 16 de jul de 2018 às 14:23, ledw <notifications@github.com>
escreveu:
