### ISSUE TITLE
Multitask with Different Data Sets?

### ISSUE THREAD

**Issue by rajicon** [facebookresearch/StarSpace#168]
Hi,

Is it possible  to train the same embeddings on 2 different tasks jointly, if the different tasks use different data sets?  For example, I have a small labelled data set I want to train on a multilabel classification task, and a large related unlabelled dataset that I want to train word vectors with.  Is this possible?  If so, is there any examples I could refer to?

**Comment by ledw** [comment]
Hi @rajicon, currently there's no way you can train these two at the same time. However, you can try the following: train your embedding on the unlabelled dataset first, then carry on training on your small labelled dataset.
