### ISSUE TITLE
How does DocSpace document recommendation works? Github documentation is very confusing.

### ISSUE THREAD

**Issue by freakeinstein** [facebookresearch/StarSpace#169]
This might be a dump question. But I wish the Starspace documentation was as simple as Fasttext's documentation.

I'm trying to train a document recommender with starspace. For that, I have followed [this](https://github.com/facebookresearch/StarSpace#docspace-document-recommendation) section.
Below is my problem in hand:
I wanted to cheat the recommendation system, to recommend some utterance from a conversation context. For that, I have downloaded Cornell Movie-Dialogs Corpus and formatted the dialogues  to match the context as detailed below.

Each line in the training input file is a context of a conversation (here 'context' mocks 'user' as in the documentation page). A context is represented by the bag dialogues between two people in that context (here 'bag of dialogues' mocks 'bag of documents' as in the documentation page). And each dialogue is a bag of words.

I have used this command for training - `starspace train -trainFile input.txt -model docspace -trainMode 1 -fileFormat labelDoc`.

So, at training time, at each step one random 'dialogue' is selected as the label and the rest of the bag of 'dialogues' are selected as input. I hope it will learn the conversation context here. 

The problem I'm facing are happening here is the prediction process. Truth is, I'm not sure how to make predictions, so I have tried what I understood from the documentation. Below is what I tried to make predictions:

I have followed [this](https://github.com/facebookresearch/StarSpace#show-predictions-for-queries) section. Executed `query_predict <model> k [basedocs]`. 
* Firstly, I'm not sure what the content or format of basedocs should be. So, I have written each  dialogue one by one without considering any context (splitting dialogues in a single conversation into separate lines).
* With above point done, I have given some input when prompted. What the prediction method did there is, finding the most similar sentence. But that's not a recommendation system should be doing. Right? It should be giving the left out item. And I'm confused how could I give multiple dialogues within a context (or while rephrasing - how to give a user for getting recommendation? Giving a user means giving a bag of documents he likes, right?). I have tried it as well by separating each dialogues within a context by <tab> delimiter. I'm not sure if that's correct.

Anyway, I guess the cheat is not working because of these,
* My assumption about the context is wrong (yes its wrong by 50% because there's no sequential learning is done, but I expects any of the opt out dialogues instead of giving the exact/best matching sentence)
* I'm formatting the 'basedocs' wrongly
* query_predict is not meant to be a tool to use in this situation.

Can someone help me to reduce my confusions and pin point the actual reason behind this behavior?

Thanks for your time.

**Comment by roundrobin** [comment]
I would be interested in that too.

**Comment by ledw** [comment]
@freakeinstein Thanks for sharing your use case of StarSpace. In the way that you train, StarSpace will learn the sentence similarity defined by context (bag of dialogs). As a result, the query_predict will select the most similar dialogue to the input, but the similarity is learned from context in your input. There is no sequential learning in StarSpace.
I hope that answer your questions.

**Comment by freakeinstein** [comment]
Thanks @ledw, I understood. I have one question. Can I give multiple inputs to the  `query_predict` so that I would get the remaining sentence in that context? Let's move my use case aside. If I'm doing collaborative filtering with Starspace (document recommendation where we input each user is represented as a bag of documents they like), how could I give input a `user` to `query_predict`? A user should be the bag of documents he/she likes. right? What's the input format? Is it like `doc1_word1 doc1_word2 doc1_wordn <tab> doc2_word1 doc2_word2 doc2_wordn <tab> docn_word1 docn_word2 docn_wordn `?

**Comment by loretoparisi** [comment]
Looking at the current example `examples/recomm_user_artists.sh`, that is using `trainMode 1` it's confusing me as well. The predictions files is like

```
Example 0:
LHS:
A190 A199 A207 A217 A227 A228 A229 A293 A298 A300 A316 A333 A344 A403 A420 A464 A498 A538 A542 A546 A548 A679 A681 A683 A687 A691 A696 A704 A1047 A1048 A1090 A1106 A1246 A1400 A1470 A1492 A1502 A1632 A1976 A2121 A2277 A2407 A2977 A3373 A3400 A3461 A3730 A5978 A9079 
RHS: 
A291 
Predictions: 
(--) [0.474973]	A229 
(--) [0.450735]	A1492 
(--) [0.4379]	A683 
(--) [0.425732]	A2277 
(--) [0.414445]	A228 
(--) [0.413803]	A65 
(--) [0.407297]	A1400 
(--) [0.388807]	A154 
(--) [0.381875]	A689 
(--) [0.374245]	A1043 
```

where the labels values should be the artist identifiers for a certain user. I'm not sure what `LHS` and `RHS` are here. While in the train and test files I have like

```
$ head -n3 /tmp/starspace/data/lastfm/user_artists.train 
AartistID
A51 A52 A53 A54 A55 A56 A57 A58 A59 A60 A61 A62 A63 A64 A65 A66 A67 A68 A69 A70 A71 A72 A73 A74 A75 A76 A77 A78 A79 A80 A81 A82 A83 A84 A85 A86 A87 A88 A89 A90 A91 A92 A93 A94 A95 A96 A97 A98 A99 A100
```

that is a mapping created by the conversion script in the example that writes out a list of artist_id from the source dataset that has a format like

```
userID	artistID	weight
2	51	13883
2	52	11690
...
3	101	13176
3	102	662
...
```

so this will create 

```
A51 A52
...
A101 A102
...
```

where each row/example defines a user implicitly and it contains the labels of the artist fanned by the user.

**Comment by ledw** [comment]
@freakeinstein Thanks for letting us know that it works for dialog context and you can use it to build a chatbot! I'd be curious to see the chatbot you built, but can totally understand if you're unable to share it. :-) 
Closing the issue now.

**Comment by freakeinstein** [comment]
@ledw Of cause I can share it with you. Currently, some manual steps need to be done to run the bot which includes Starspace training ('cause there is no python wrapper 😟), and I'm trying to move data from memory to a disk (with whoosh). I can use next 10 days for that. I can't afford to host it, to give a demo. I think, I could share the source repo. Where should I share it? Here?

**Comment by ledw** [comment]
@freakeinstein thanks! You can share it here, or you can reach me by email: ledell@fb.com.

**Comment by loretoparisi** [comment]
@freakeinstein that's awesome! 💯Hopefully @ledw is going to add this as good example of using Starspace, because this part is completely missing so far.

**Comment by freakeinstein** [comment]
@ledw Here is the repo link: [https://github.com/a-mma/QnA-baker](https://github.com/a-mma/QnA-baker). I have added a Readme file and hopes it will help you through manual steps. It currently is in duct taped form. Please tell me if there is an issue. If you find any license violations, please let me know as well. Because, I wish to improve the code. Thanks.

@loretoparisi  Thanks, I hope so. 😊

**Comment by loretoparisi** [comment]
@freakeinstein thank you! Congrats this project rocks! 💯
