### ISSUE TITLE
Do order of words matter for docspace?

### ISSUE THREAD

**Issue by thisisandreeeee** [facebookresearch/StarSpace#179]
My understanding of docspace is that it tries to learn which documents are usually selected by the same users, by minimizing the loss function with `a` being all the selected items but one, and `b` being that left out item. Because each document is represented by a bag of words, we are able to update the vector representations of each individual word with each iteration of SGD.

My question is, do the order of words within this bag of words representation matter? It certainly would matter for learning tasks with regards to sentences, but I'm not sure if this assumption holds for docspace.

**Comment by jaseweston** [comment]
Starspace does not currently make use of word order, although you could encode n-grams or the like by adding them explicitly as features.

**Comment by thisisandreeeee** [comment]
Thanks for the clarification! Could you provide a little more information
on how I may encode n-grams as features?

**Comment by jaseweston** [comment]
Only in a very dumb way right now:
You could add things like   "Bruce_Willis" to your set of features

**Comment by thisisandreeeee** [comment]
Ah, that's an interesting thought. Thank you for your input!
