### ISSUE TITLE
How to embed the sentence? 

### ISSUE THREAD

**Issue by daridar** [facebookresearch/StarSpace#180]
I trained starspace model on my corpus then I want to create an embedding of my sentences. 
For example, I have a .txt file with each sentence separated by new line. Each token separated by space. 
Or I want to embed just one sentence, which I pass to the model like this: 
```
make embed_mod
./embed_doc model_starspace ["This is a sentence ."]
```
or: 
`./embed_doc model_starspace path_to.txt 
`
Every time I receive this output: 

> Start to load a trained starspace model.
> STARSPACE-2017-2
> Model loaded.
> file cannot be opened for loading!

What can I fix this issue? 
And how to same all embeddings from .txt file for example to pickle or csv? 

Ubuntu 16.04

**Comment by ledw** [comment]
Hi @daridar , for your first example, you should just run 
`./embed_doc model_starspace `
after the model is loaded, try input 
`"This is a sentence."`

For your second command, as long as there's a file path_to.txt, it should work as expected.

**Comment by ledw** [comment]
Closing old issue.
