### ISSUE TITLE
Random seed initialization

### ISSUE THREAD

**Issue by fedorn** [facebookresearch/StarSpace#185]
Hello! Is it possible to add the ability to initialize random seed for better reproducibility of results obtained with StarSpace?

**Comment by jwijffels** [comment]
+1 for having such a feature!

**Comment by ledw** [comment]
@fedorn Thanks. We'll consider to add that.

**Comment by ledw** [comment]
@fedorn @jwijffels We can add the ability to initialize random seed, however, you need to set `-thread 1` in order to obtain reproducibility as we use hogwild in training and it's not thread safe. Do you think it's still useful to have the feature running with only one thread?

**Comment by fedorn** [comment]
@ledw No, that probably wouldn't be useful for me. Thank you for looking into it.

**Comment by ledw** [comment]
@jwijffels: I'm afraid that this is something we couldn't fix: the hogwild is a lock-free algorithm that let each thread modify the embeddings without locks. I think if we implement lock-safe algorithm to update the embedding tables, then it's likely to be much slower. I'd like to close the task for now.

**Comment by jwijffels** [comment]
Ok, thank you for the feedback on the reason, that makes things clear.
