### ISSUE TITLE
test mode load only part of the testFile content

### ISSUE THREAD

**Issue by puppyapple** [facebookresearch/StarSpace#189]
I have successfully train a model with tagspace model. But when I use the model to test for a testfile containing about 5million records, it loaded only 4500 examples around. Is that because there's a limitation for test records size?

**Comment by ledw** [comment]
@puppyapple There's no limitation for test. How did you run the command to evaluate your model? Did you set the same parameters as training? Is your test file of the same format of training?

**Comment by puppyapple** [comment]
@ledw thanks for the reply. My commands used are as below:
Training command: 
/usr/Starspace/starspace train -trainFile ../Data/Input/fasttext/train_data -validationFile ../Data/Input/fasttext/valid_data -validationPatience 20 -dim 200 -minCount 5 -minCountLabel 100 -ngrams 5 -verbose 1 -thread 32 -model tagspace_01 -label '#'
Testing command: 
/usr/Starspace/starspace test -testFile  ../Data/Input/fasttext/test_data_weighted -predictionFile test02 -verbose 1 -thread 32 -model tagspace_02 -label '#' -K 10

One thing that I forgot to mention: the testFile that I used does not actually has groud true labels(unlabeled data), so I use "#ID #Name" in each file for binding text data with their IDs and names(but somehow this won't work. I think it's because IDs and names don't show in dictionary of model?) Would this cause that the test process load only part of the testFile contents?

**Comment by puppyapple** [comment]
@ledw for the first problem, I've tried one way that seems to work: 
for the testFile with data unlabeled, I added '#mylabel' in each record where 'mylabel' is a label that apprears more than minCountLabel times in my training data. And then I run 'starspace test' at the new testFile, it can output prediction file.
But one new issue is that the output is a little bit less then the testFile record lines(testFile with 5887248 lines but 5812237 for the output result by 'starspace test' command). And because of this, I could not attach the output result with my record ID for further analysis.

**Comment by puppyapple** [comment]
@ledw For the lost count of test examples, I think it's like what you mentioned, some examples have been filtered because of the 0 word/label in dictionary. Since each of my examples has a unique ID, I want to attach the test result with the IDs. If some of the examples will be filtered, then I cannot do the link after testing. Is there any suggestion?(Or I have to find the filtered examples by doing statistics with minCount and minCountLabel myself?)

For the initModel situation, my case in detail is like this:
I have a multi-label text data set which I want to train a classification model, to predict another larget set of text data unlabeled. I'm afraid that the two  data set are not exactly from the same distribution, so I trained a w2v with fasttext, and transformed it to .tsv format, with which I want to initialize my classification model(-trainMode 0), like a semi-supervised learning. It is sure that most of the label words doesn't not show in the w2v embeddings. I guess that's why I got the "ERROR"?

Thanks again for the reply.

**Comment by puppyapple** [comment]
Any good idea to match with IDs?

**Comment by ledw** [comment]
@puppyapple sorry for the delay in replying. For the ID match case, I think what you suggested is reasonable: i.e. adding a prefixID for test examples. If you would like, you can try to add that and send out a PR (let me know if you need any help).

For problem with initModel, you can try to add 0 vectors (or whatever vector you'd like to initialize with) for labels that does not appear in train set, to the trained .tsv file. That should solve your problem.

**Comment by puppyapple** [comment]
@ledw Thanks. I'm not so familiar with C++ but I will give it a try.
