### ISSUE TITLE
embed_doc outputs NaNs

### ISSUE THREAD

**Issue by hakami1024** [facebookresearch/StarSpace#191]
With one of my trained models embed_doc returns bunch of nans (more precisely: -nan -nan -nan ...) for some texts (at least for one) (but not for all texts, so this event is generally rare).

Is this behaviour normal? What reasons could cause it? I'm trying to train on increased dataset now, but I'm not sure, if that will help for any future input.

**Comment by hakami1024** [comment]
Uploaded the example to google drive:
(https://drive.google.com/open?id=1Mf6yi1eYYemisRJjZabQySR_ZAcUbEkE)
found_text.txt contains the problematic input for embed_doc.
products_search_categorical and products_search_categorical.tsv are model files. If my checking script was good enough, the .tsv file does not contain nans.

**Comment by ledw** [comment]
@hakami1024 Thanks for providing the examples. This is a tricky one: I think you turned on -useWeight in your training, where the model assumes that the input comes from the form "word_1:weight_1" where weight1 is numerical. However, in the test example, there's "feature:infant", so the model parses that the word feature has infinite weight ("inf"). To fix this, you can change the ':' in your training examples by some other character ("_" for instance). We'll make the error message more informative and add an option to specify the separator to some other character.

**Comment by ledw** [comment]
A new flag is added to specify weights in https://github.com/facebookresearch/StarSpace/pull/205.
