### ISSUE TITLE
Repeated items in labelDoc

### ISSUE THREAD

**Issue by roundrobin** [facebookresearch/StarSpace#193]
Hey guys,

without even noticing we created a labelDoc file that had repeated labels in the file (around 10k lines/entries), but nonetheless, the predictions were okay.

Still, we wanted to get rid of the duplicated lines, to have a better space to predict from, but now the predictions aren't that good anymore.

On a higher level, we're now wondering what Starspace predicts when the labelDoc file contains repeated entries?

**Comment by ledw** [comment]
@roundrobin question for clarification: I think you meant for basedoc file, not labelDoc? labelDoc is a fileFormat, and we use -basedoc flag to indicate candidates to be included in prediction.

**Comment by roundrobin** [comment]
@ledw of course I meant basedoc, sorry my bad.

**Comment by ledw** [comment]
@roundrobin yes the labelDoc file can contain repeated items. The predict function will treat them as separate entities. It could be the case that your training data also contain a lot of duplicated items, which implicitly reflect the distribution of your data. If you remove the duplications in labelDoc file, it is no longer from the same distribution of your training data, and thus the model quality is degraded.

**Comment by ledw** [comment]
Closing the task as there's no recent update.
