### ISSUE TITLE
Multi Relational Example Doesn't use Train Mode 4

### ISSUE THREAD

**Issue by nrlewis** [facebookresearch/StarSpace#195]
Maybe I missed this is  the docs, but the README says that trainmode 4 is for multirelational graphs, but then the example uses trainmode 0. 

If we were using train mode 4 for multirelational learning, what would the format look like? 

Would the following work?
```
node_1 edge_1 __label__node_2
```

**Comment by ledw** [comment]
@nrlewis Hi, if you use train mode 4, the format would be:
`edge_1  __label__node_1  __label__node_2`

**Comment by nrlewis** [comment]
Hi @ledw , Thank you for your response.  

A couple more questions: How do I make a query then? 

```
<edge> __label__<node_1> ?
```

When initializing the vectors, I noticed that I have to make them `__label__<node>`,  is it useless to have nodes without the `__label__` prefix in graph training? 

Is there a way to freeze the initial embedding weights ?

**Comment by ledw** [comment]
@nrlewis yes, you can query like that.
What do you mean by 'useless' to have nodes without the `__label__` prefix? Currently there's no way to freeze the initial embedding weights.

**Comment by nrlewis** [comment]
@ledw, thank you for the response.  By "useless" I mean that I initialized a lot of words without the __label__ prefix in the into model and I got an error.  So I added the __label__ to all the words in the initial model.     Does the __label__ prefix have any meaning if all the words in the embedding space have it?

**Comment by ledw** [comment]
@nrlewis You should be able to initialize your model with lots of words without the `__label__` prefix as long as it does contain some label in your initial model. 
It still has a meaning if all the words in the embedding space has `__label__` prefix, for instance, in the user page recommendation case (https://github.com/facebookresearch/StarSpace/#pagespace-user--page-embeddings) , all words has the `__label__` prefix.

**Comment by ledw** [comment]
Closing task as there's no recent update.

**Comment by tharangni** [comment]
1. If the example script trains on mode 0 instead of 4, then it is just basically creating document-label embeddings?
2. ``` edge_1 __label__node_1 __label__node_2``` : Over here, edge_1 refers to the kind of relation that exists between node_1 and node_2? Or does it just signify a (directed) edge between these nodes? For instance: ``` born_in  __label__obama  __label__hawaii ``` would represent an example relation between two nodes?
