### ISSUE TITLE
Online Learning

### ISSUE THREAD

**Issue by DavidDavidsonDK** [facebookresearch/StarSpace#198]
is there any way for training already trained embeddings? I mean that if i already train model  on some text and the new words will come , can i train the new embeddings without fitting the whole dataset again?

**Comment by ledw** [comment]
@DavidDavidsonDK Hi, currently we can train embeddings from already trained ones, with the flag `--initModel`. However, it does not support adding new words in the model dictionary -- it loads a model from the file specified (can be in .tsv) format and builds a dictionary from the model file.

**Comment by DavidDavidsonDK** [comment]
thanks
