### ISSUE TITLE
Unsupervised topic classification

### ISSUE THREAD

**Issue by helgasvala** [facebookresearch/StarSpace#199]
Hey! 

For topic classification, I want to compare StarSpace to LDA, which is unsupervised so in order to have a fair comparison I want to make my own embeddings for StarSpace first. My question is, once I make the embeddings, can I somehow divide them up to as many topics as I set as parameters in the LDA? How could I extract clusters from the embeddings?

Thank you so much!

**Comment by ledw** [comment]
@helgasvala Hi, you could try standard clustering methods on embeddings trained from StarSpace. I'd suggest to try a different set of number of clusters to form, in order to compare with topics from LDA.
