### ISSUE TITLE
Understanding the output

### ISSUE THREAD

**Issue by helgasvala** [facebookresearch/StarSpace#200]
Hey! I have a really basic question that I can't seem to find an answer to. In the prediction files, I want to understand what the output means, like this pagespace (recomm_user_artists.sh) example from the README. 

As an example, I get:

Example 27:
LHS:
A53 A56 A64 A65 A70 A80 A88 A154 A199 A203 A207 A210 A220 A228 A424 A432 A511 A709 A735 A969 A982 A1073 A1099 A1106 A1394 A1396 A1397 A1398 A1408 A1410$
RHS:
A84
Predictions:
(--) [0.602615] A1396
(--) [0.586171] A1408
(--) [0.566579] A1397
(--) [0.549347] A1398
(--) [0.505462] A70
(--) [0.504954] A1394
(--) [0.503935] A80
(--) [0.488138] A1409
(--) [0.483712] A56
(--) [0.480524] A15079

Sometimes (in other examples) you get (++) in front. My question is, what does the --/++ mean and what do the numbers mean? Percentage? Which kind?

Thank you so much.

**Comment by ledw** [comment]
@helgasvala Hi, the (++) means that it is correct prediction of RHS, (--) means it is not. The numbers are predicted scores for the item (could be cosine or dot product between LHS and RHS, depending which similarity measure you use. We'll update that in README.

**Comment by ledw** [comment]
@helgasvala yes that means none of them are correct. It meant to be a example script to demonstrate how to use the pagespace so the parameters are not necessarily optimized.

**Comment by DinaS18** [comment]
@ledw Hello! Could you explain why the negative predictions retrieved include the artists which are in LHS? Shouldn't it give negative labels from the rest of the dictionary? Thanks
