### ISSUE TITLE
R package wrapping Starspace on CRAN

### ISSUE THREAD

**Issue by jwijffels** [facebookresearch/StarSpace#209]
Hi @ledw
this is a message to inform you that I've put the R package wrapping the starspace C++ library on CRAN. I called it ruimtehol. The R package is available at https://CRAN.R-project.org/package=ruimtehol and the development is done at https://github.com/bnosac/ruimtehol. The package is licensed under MPL-2.0 and includes the PATENTS file as well as the BSD license information from Facebook.
Regarding functionalities:

- It's built on Starspace STARSPACE-2017-2.
- It allows all functionalities that Starspace provides, directly available to R users on any platform.
- This means: low-level Starspace model building functionalities and higher level model building, functionalities and apps, namely:

| Function                      | Functionality                                                  |
|-------------------------------|----------------------------------------------------------------|
| `starspace`                   | Low-level interface to build a Starspace model                 |
| `starspace_load_model`        | Load a pre-trained model or a tab-separated file               |
| `starspace_save_model`        | Save a Starspace model                                         |
| `starspace_embedding`         | Get embeddings of documents/words/ngrams/labels                |
| `starspace_knn`               | Find k-nearest neighbouring information for new text           |
| `starspace_dictonary`         | Get words/labels part of the model dictionary                  |
| `predict.textspace`           | Get predictions along a Starspace model                        |
| `as.matrix`                   | Get words and label embeddings                                 |
| `embedding_similarity`        | Cosine/dot product similarity between embeddings - top-n most similar text                  |
| `embed_wordspace`             | Build a Starspace model which calculates word/ngram embeddings                              |
| `embed_sentencespace`         | Build a Starspace model which calculates sentence embeddings                                |
| `embed_articlespace`          | Build a Starspace model for embedding articles - sentence-article similarities              |
| `embed_tagspace`              | Build a Starspace model for multi-label classification                                      |
| `embed_docspace`              | Build a Starspace model for content-based recommendation                                    |
| `embed_pagespace`             | Build a Starspace model for interest-based recommendation                                   |
| `embed_entityrelationspace`   | Build a Starspace model for entity relationship completion                           

I must say I'm pretty satisfied with the model, it really gives nice & interpretable results on the datasets which I used it already and it's very flexible for all kinds of situations. @ledw & @jaseweston Many thanks!
@davidalbertonogueira thanks for having created the windows fixes, without this, this would not have been possible.

**Comment by davidalbertonogueira** [comment]
Happy to see the fruits of my Windows port!
