### ISSUE TITLE
Does this algorithm work on audio data?Can any body give me an example to use this algorithm for audio data classification?

### ISSUE THREAD

**Issue by SibtainRazaJamali** [facebookresearch/StarSpace#213]

**Comment by LAV42** [comment]
If you obtain a feature vector for your clip through a neural network, you could use these features and do just like in the image example:
https://github.com/facebookresearch/StarSpace#imagespace-learning-image-and-label-embeddings

**Comment by ledw** [comment]
@SibtainRazaJamali yes, as @LAV42 mentioned, you can use it similar to the image example. Let us know if you have any other questions.

**Comment by SibtainRazaJamali** [comment]
Yes @LAV42 and @ledw Thanks for kind response , i can implement this but can you suggest me ,if there is any specific algorithm to extract important features from audio signal. Since spectogram of audio signal contains different features as compared to normal image.

**Comment by ledw** [comment]
@SibtainRazaJamali Apologize for the delay in replying. I am not familiar with algorithms to extract features from audio signal.
