### ISSUE TITLE
Problem with negSearchLimit / maxNegSamples. Model continues search negative examples and exceeds maxNegSamples.

### ISSUE THREAD

**Issue by Gevorg-Minasyan** [facebookresearch/StarSpace#215]
https://github.com/facebookresearch/StarSpace/blob/ca38dee97228bf460be592231f9732a296dddf2f/src/model.cpp#L440-L442
I think there should be `break` instead of `continue` in `trainOneBatch` method.

**Comment by ledw** [comment]
Thanks for reporting. Fixed in https://github.com/facebookresearch/StarSpace/pull/216/commits/1b28b9b2cf6866a73ed7d03d7f150e0888b35e75.

**Comment by jwijffels** [comment]
I'm interested. So setting maxNegSamples never had any effect, only negSearchLimit  had up to this fix?

**Comment by ledw** [comment]
@jwijffels It was a bug introduced in 8790244ebb37ebc39ac72562ea7678591289286a and needs to be corrected. maxNegSamples does have effect on speed and accuracy.

**Comment by jwijffels** [comment]
Ah ok. Thanks, good to know. I'm still using STARSPACE-2017-2 so there it was still fine.
