### ISSUE TITLE
python - Information Retrieval

### ISSUE THREAD

**Issue by ctrado18** [facebookresearch/StarSpace#223]
Hi,

I have some question to the python wrapper. Is the Information Retrieval part already implemented? As the infos are a bit sparse but it seems that can get now document vectors from a labeled data set? but the test data seems unlabeled. What format I need for labeled documents?

I suppose question and answer need to be trained together somehow, so a docvec seems not enough.

Thanks.

**Comment by freakeinstein** [comment]
@ctrado18  I believe you are referring to the [Utility functions](https://github.com/facebookresearch/StarSpace#utility-functions) available for StarSpace binary. The python library doesn't bind those utility functions. The utility functions are backed by the StarSpace class, which is actually binded in the python wrapper. So, if you want to achieve those high-level functionalities, you need to implement the [same idea](https://github.com/facebookresearch/StarSpace/tree/master/src/apps) in python.

Additional info: Bindings for `getNgramVector`, `printDoc`, `predictOne` are available [here](https://github.com/facebookresearch/StarSpace/pull/221)
