### ISSUE TITLE
Error while setting up python binding

### ISSUE THREAD

**Issue by Arjunsankarlal** [facebookresearch/StarSpace#226]
I followed all the steps as mentioned... But when I try to run the last step of running the `./build.sh` I get this following error 

> Scanning dependencies of target starwrap
[ 50%] Building CXX object CMakeFiles/starwrap.dir/starspace_pybind.cc.o
/Users/arjun-zt235/Projects/Github_Test/StarSpace/python/starspace_pybind.cc:63:11: error: no matching constructor for initialization of
      'py::buffer_info'
                        return py::buffer_info(
                               ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:28:5: note: 
      candidate constructor not viable: cannot convert initializer list argument to 'detail::any_container<ssize_t>' (aka 'any_container<long>')
    buffer_info(void *ptr, ssize_t itemsize, const std::string &format, ssize_t ndim,
    ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:39:5: note: 
      candidate constructor template not viable: requires 3 arguments, but 6 were provided
    buffer_info(T *ptr, detail::any_container<ssize_t> shape_in, detail::any_container<ssize_t> strides_in)
    ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:46:5: note: 
      candidate constructor template not viable: requires 2 arguments, but 6 were provided
    buffer_info(T *ptr, ssize_t size)
    ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:83:5: note: 
      candidate constructor not viable: requires 7 arguments, but 6 were provided
    buffer_info(private_ctr_tag, void *ptr, ssize_t itemsize, const std::string &format, ssize_t ndim,
    ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:42:5: note: 
      candidate constructor not viable: requires 4 arguments, but 6 were provided
    buffer_info(void *ptr, ssize_t itemsize, const std::string &format, ssize_t size)
    ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:49:14: note: 
      candidate constructor not viable: requires at most 2 arguments, but 6 were provided
    explicit buffer_info(Py_buffer *view, bool ownview = true)
             ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:56:5: note: 
      candidate constructor not viable: requires 1 argument, but 6 were provided
    buffer_info(const buffer_info &) = delete;
    ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:59:5: note: 
      candidate constructor not viable: requires single argument 'other', but 6 arguments were provided
    buffer_info(buffer_info &&other) {
    ^
/Users/arjun-zt235/.conan/data/pybind11/2.2.3/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/buffer_info.h:26:5: note: 
      candidate constructor not viable: requires 0 arguments, but 6 were provided
    buffer_info() { }
    ^
1 error generated.
make[2]: *** [CMakeFiles/starwrap.dir/starspace_pybind.cc.o] Error 1
make[1]: *** [CMakeFiles/starwrap.dir/all] Error 2
make: *** [all] Error 2
/Users/arjun-zt235/Projects/Github_Test/StarSpace/python
#############################  run test ############################# 
cp: ./build/starwrap.so: No such file or directory
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import starwrap as sw
ModuleNotFoundError: No module named 'starwrap'

I am using mac and I have python3.7 installed in my system. Have anyone faced this issue?

**Comment by Arjunsankarlal** [comment]
Additional Information

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

**Comment by mobstazinc** [comment]
i meet the same issues. is there anyone have any solution for this?

**Comment by freakeinstein** [comment]
@Arjunsankarlal @mobstazinc Was able to reproduce the issue on MacOS mojave (10.14) See the pull request above for fix.

Additional info: Build script updated to use `pybind11/2.2.4`.

**Comment by ledw** [comment]
@freakeinstein Thanks for helping. Is this fixed? Can we close the issue?

**Comment by Arjunsankarlal** [comment]
Yeah it is working properly now :)
