### ISSUE TITLE
TagSpace: Missing Dataset

### ISSUE THREAD

**Issue by zeyuanchen23** [facebookresearch/StarSpace#228]
The link to [AG's News Topic Classification Dataset](https://github.com/mhjabreel/CharCNN/tree/master/data/ag_news_csv) is not available now. Also, [this script](https://github.com/facebookresearch/Starspace/blob/master/examples/classification_ag_news.sh) cannot download the datasets.

**Comment by ledw** [comment]
@zeyuanchen23 Hi, the script should still work -- you should be able to download the datasets using that script. What issue did you encounter?

**Comment by zeyuanchen23** [comment]
@ledw Hi! Thanks for getting back. It works now. I got some permission issues and it was solved by running chmod 777.
