### ISSUE TITLE
How I should use initModel in training

### ISSUE THREAD

**Issue by bastia1989** [facebookresearch/StarSpace#233]
In learning the mapping between entities and relations , if I have already had a embedding matrix for the vocabulary, what is the correct form of the file for `-initModel` parameter.

**Comment by jwijffels** [comment]
it's a binary or tsv file with the model you save in a previous run using the -model argument

**Comment by bastia1989** [comment]
> it's a binary or tsv file with the model you save in a previous run using the -model argument

Thanks.

**Comment by bastia1989** [comment]
> it's a binary or tsv file with the model you save in a previous run using the -model argument

Would you give me some clue on how starspace train such relation model? What I can infer is that the embedding vectors of the two entities are feed into a network so the output could be a softmax prediction? Would you give more details, thanks.
