### ISSUE TITLE
question regarding multi relation example training mode

### ISSUE THREAD

**Issue by tharangni** [facebookresearch/StarSpace#239]
From issue #195 
1. If the example script trains on mode 0 instead of 4, then it is just basically creating document-label embeddings?
2. ``` edge_1 __label__node_1 __label__node_2``` : Over here, edge_1 refers to the kind of relation that exists between node_1 and node_2? Or does it just signify a (directed) edge between these nodes? For instance: ``` born_in  __label__obama  __label__hawaii ``` would represent an example relation between two nodes?

**Comment by tharangni** [comment]
any update??

**Comment by ledw** [comment]
@tharangni for 1, yes. We found that trainMode 4 was not necessary. We're considering to take it off and simply it.
2. Yes, in trainMode 4 that's the correct interpretation.
