### ISSUE TITLE
How are document (vectors) represented in document classification

### ISSUE THREAD

**Issue by tharangni** [facebookresearch/StarSpace#246]
In training mode 0, I understand that starspace creates word ngrams from all the words in the training file for generating vectors and stores these vectors in the .tsv file. And then from these words, it creates a document embedding vector for the respective document; compares it with the label embedding and minimises the similarity objective. 

How are the document vectors generated from the word vectors here? 

I ran a small experiment using the python wrapper:

```
arg = sw.args()
arg.trainFile = './cooking.txt'
arg.testFile = './cooking.se.txt'
arg.trainMode = 0
arg.ngrams = 1
arg.verbose=2
arg.normalizeText = True
arg.p = 0

sp = sw.starSpace(arg)
sp.init()
sp.train()

sp.saveModel('cooking-model')
sp.saveModelTsv('cooking-model.tsv')

sp.initFromSavedModel('cooking-model')
sp.initFromTsv('cooking-model.tsv')

sp.evaluate()
v = np.array(sp.getDocVector('this is', ' '))
w = np.array(sp.getDocVector('is this', ' '))
np.allclose(v, w) --> True

t = np.array(sp.getDocVector('this', ' '))
s = np.array(sp.getDocVector('is', ' '))
np.allclose((t+s), v) --> False
```

I know that the vectors are created after undergoing some operation for creating document vectors but I am not sure which one. I tried min, max, avg but they're not resulting in the same document vector `v` .

Any help would be highly appreciated!

**Comment by jwijffels** [comment]
FYI. Had a similar discussion on the topic here: https://github.com/bnosac/ruimtehol/issues/6

**Comment by tharangni** [comment]
@jwijffels okay. but even though i try to compute the vector as it is mentioned in the discussion, i.e, `-p normalization parameter: we normalize sum of embeddings by deviding Size^p, when p=1, it's equivalent to taking average of embeddings; when p=0, it's equivalent to taking sum of embeddings. [0.5]` , i don't get the same doc vector when i take the sum of its respective word vectors with `ngram = 1, p=0 ` .

**Comment by jwijffels** [comment]
Well the ruimtehol r wrapper does give that when ngrams is set to 1. Probably you have no set p when lading your model again

**Comment by tharangni** [comment]
p remains 0 when i load my model again. but there seems to be another term apart from p called as `norm` in the python binding. 
if norm = 0 & p = 0, my resulting vectors are all 0 for the model. 
if norm = 1 & p = 0, i get real valued vectors, but my problem in the question still persists.

so i wonder if it has anything to do with the norm parameter (?) or is my implementation incorrect???

**Comment by jwijffels** [comment]
in Starspace (see also my note at https://github.com/bnosac/ruimtehol/issues/6) in case of dot similarity division is done by dividing the sum by the Size^p, for cosine similarity it is divided by the euclidean norm

**Comment by tharangni** [comment]
aha! yes. it seems i was using cosine similarity. it works fine with dot product. i didn't read it properly.
thanks for your help!

**Comment by ledw** [comment]
@jwijffels thanks for helping with this question. @tharangni It seems that your question is resolved? Can I close the issue now?
