### ISSUE TITLE
Calculating time taken to predict

### ISSUE THREAD

**Issue by tharangni** [facebookresearch/StarSpace#247]
I am doing a document classification task and my test set is quiet large: around 250k samples to be compared against 55k labels. Is there a way to calculate the time it takes to predict for these samples? I know it works fine since I can predict for 10k samples (even though it takes like 5-10 mins). 
Issue #68 was also referred and i changed the number of threads from 10 to 50, but it still takes time.

**Comment by ledw** [comment]
@tharangni Hi, the time it takes in test is proportional to the size of the examples, so it takes 25x more time when you increase examples from 10k to 250k.

**Comment by tharangni** [comment]
Awesome! Thanks for the info! Closing it .
