### ISSUE TITLE
Dealing with position bias

### ISSUE THREAD

**Issue by travisbrady** [facebookresearch/StarSpace#252]
What is the recommendation for Starspace usage for ranking and recommendation problems where the training data may be biased due to position effects or trust?

For example given training data from a status quo recommender that displays 5 recommended products in positions 1-5 and training with mode=5. Does Starspace provide capabilities here? 
Is it best to simply add an example weight corresponding to examination probability?

thank you

**Comment by ledw** [comment]
@travisbrady Hi, there's no option specifically for position effect, but I think adding example weight corresponding to examination probability as you suggested should work.
