### ISSUE TITLE
[Question] Does StarSpace support char based embedding

### ISSUE THREAD

**Issue by laifi** [facebookresearch/StarSpace#256]
Hello ,
Does StarSpace supports char based embedding as in Fasttext using :
```
  -minn               min length of char ngram [0]
  -maxn               max length of char ngram [0]
```
Otherwise, it would be a good feature enhancement :+1:

**Comment by ledw** [comment]
@laifi Hi, currently it does not support char based embedding.

**Comment by nickyongzhang** [comment]
@ledw Any plan of adding this useful function. Char-based embedding is where the power of fasttext compared with classic word2vec, isn't it?

**Comment by ledw** [comment]
@ledw It is not on our list. Note that in the classification task of fasttext, the Char-based embedding is not supported.
