### ISSUE TITLE
Citation: arXiv or AAAI

### ISSUE THREAD

**Issue by nzw0301** [facebookresearch/StarSpace#264]
I have a question about a reference to cite the StarSpace paper.  `README.md` suggests to cite arXiv version, but StarSpace paper has also been accepted at AAAI 2018. Personally, AAAI version is better because it is a newer one and not pre-print. So, which version should I cite?

**Comment by jaseweston** [comment]
sure, the AAAI one is fine!

**Comment by nzw0301** [comment]
Thank you for your quick answer!
