### ISSUE TITLE
Will there be good support for image tasks? Or will support image tasks in the future?

### ISSUE THREAD

**Issue by csyking** [facebookresearch/StarSpace#36]

**Comment by jaseweston** [comment]
yes!! we are planning to add very soon! will update this when done.

**Comment by ledw** [comment]
Hi @csyking: we just added support for image feature and an example of how to use it:
https://github.com/facebookresearch/Starspace/#imagespace-learning-image-and-label-embeddings
Please check it out!

Closing the task.
