### ISSUE TITLE
Recommend Different Boost Install Location

### ISSUE THREAD

**Issue by jsawruk** [facebookresearch/Starspace#37]
On newer versions of Mac OS X, the directory `/usr/bin` is read only due to SIP. Recommend changing the Boost install directory to `/usr/local/bin` so users do not need to disable SIP to compile. See this [StackOverflow](https://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled) for more info.

I installed to `/usr/local/bin`, changed the `makefile` and it compiled correctly. I don't think this will cause any conflict on other operating systems.

**Comment by ledw** [comment]
Thanks for the recommendation. It's now changed to /usr/local/bin by https://github.com/facebookresearch/Starspace/commit/45c304c96f1f7da6a906ebf76bbd325d9c908983 and https://github.com/facebookresearch/Starspace/commit/ae59765a02077153d6d84494a5388182072602db.

Closing the issue now.
