### ISSUE TITLE
Do you guys plan to change the current license? 

### ISSUE THREAD

**Issue by sumanp** [facebookresearch/StarSpace#38]

**Comment by jaseweston** [comment]
We are looking into a more permissive license, yes. Will update here soon.

**Comment by avr248** [comment]
Will something change about the license?

**Comment by ledw** [comment]
@avr248: as @jaseweston mentioned, we're working on getting a more permissive license. However it takes some time to do so. Stay tuned and we'll update here.

**Comment by ledw** [comment]
@sumanp @avr248 we updated the license to BSD license. 
Closing the issue.

**Comment by halflings** [comment]
The license is still the infamous "BSD + Patents" license that facebook retracted from React and other projects.
Would it be possible to switch to MIT like for those projects?

(as you might imagine, the content of PATENTS makes this project hard/impossible to use by larger companies because of the legal implications)

**Comment by jaseweston** [comment]
Other projects from FAIR also have this license, right? E.g. ParlAI,
fastText, etc.  Do we have one that doesn't? I'm not sure.

**Comment by timkpaine** [comment]
As always with the many other libraries this has applied to, do not use this library if you work at a company:
https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2

**Comment by jwijffels** [comment]
fasttext dropped the PATENTS file: https://github.com/facebookresearch/fastText/issues/650
why not starspace?

**Comment by ledw** [comment]
@halflings @timkpaine @jwijffels we changed the license to MIT now: https://github.com/facebookresearch/StarSpace/commit/a5c7ea6a3cd1646bfe57c629a552da318b854d92

**Comment by jwijffels** [comment]
many many thanks for the generousity on the license change!!
