### ISSUE TITLE
Starspace crashes while testing model

### ISSUE THREAD

**Issue by disdi** [facebookresearch/StarSpace#42]
While running ./examples/classification_ag_news.sh, ./examples/wikipedia_article_search.sh, I find Starspace is crashing while testing.

My system details -

sakets@mobile-graphics-ml:/mnt/hdd/sakets/facebook/Starspace$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
sakets@mobile-graphics-ml:/mnt/hdd/sakets/facebook/Starspace$ uname -a
Linux mobile-graphics-ml 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Attaching the log file with shows the error at -

starspace: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
./examples/classification_ag_news.sh: line 75: 29692 Aborted                 (core dumped) ./starspace test -model "${MODELDIR}"/ag_news -testFile "${DATADIR}"/ag_news.test -ngrams 1 -dim 10 -label "__label__" -thread 10 -similarity "dot" -trainMode 0 -verbose true

[error.zip](https://github.com/facebookresearch/Starspace/files/1308883/error.zip)

**Comment by ledw** [comment]
@disdi seems like some problem with the binary saved file in your version. Could you try first if the .tsv file works for you? You can try that by changing the first line to the following in ./starspace test (no need to change anything in ./starspace train):
`./starspace test -model "${MODELDIR}"/ag_news.tsv`

Please let me know if the .tsv format model works for you or not.

**Comment by disdi** [comment]
On running the below command -
./starspace test -model "${MODELDIR}"/ag_news.tsv, I get the below error -

Start to evaluate trained model:
Empty test file or model path.

"starspace train ..."  or "starspace test ..."

The following arguments are mandatory for train:
  -trainFile       training file path
  -model           output model file path

The following arguments are mandatory for test:
  -testFile        test file path
  -model           model file path

However I ran the starspace with valgrind with below changes-

diff --git a/examples/classification_ag_news.sh b/examples/classification_ag_news.sh
index 49483cb..d7e5207 100755
--- a/examples/classification_ag_news.sh
+++ b/examples/classification_ag_news.sh
@@ -44,7 +44,7 @@ make

 echo "Start to train on ag_news data:"

-./starspace train \
+G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --log-file=valgrind_train.log  ./starspace train \
   -trainFile "${DATADIR}"/ag_news.train \
   -model "${MODELDIR}"/ag_news \
   -initRandSd 0.01 \
@@ -63,7 +63,7 @@ echo "Start to train on ag_news data:"

 echo "Start to evaluate trained model:"

-./starspace test \
+G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --log-file=valgrind_test.log ./starspace test \
   -model "${MODELDIR}"/ag_news \
   -testFile "${DATADIR}"/ag_news.test \
   -ngrams 1 \
diff --git a/makefile b/makefile
index f36a01e..fd9f18a 100644

I do not get any crash, though both training and testing tool long time to complete.
Attaching valgrind logs.
[valgrind_logs.zip](https://github.com/facebookresearch/Starspace/files/1312298/valgrind_logs.zip)

**Comment by ledw** [comment]
@disdi sorry I did not specify the full command to you. For .tsv format model you should try:
```
./starspace test 
-model "${MODELDIR}"/ag_news.tsv
-testFile "${DATADIR}"/ag_news.test 
-ngrams 1 
```

I'll take a look at the logs. How long does it take to complete when you run it with valgrind?

**Comment by disdi** [comment]
Please find the result of below command
./starspace test -model "${MODELDIR}"/ag_news.tsv -testFile "${DATADIR}"/ag_news.test -ngrams 1 

attached in the file.
[tsv_format.TXT](https://github.com/facebookresearch/Starspace/files/1313006/tsv_format.TXT)

Valgrind training alone took more than 6 hours. Running the full example script (both training and testing ) was an overnight thing (10-12 hours) with valgrind.

**Comment by disdi** [comment]
@ledw  Any update on this ?

**Comment by ledw** [comment]
@disdi thanks. It looks like the tsv model works fine -- i.e. it gives you the evaluation metric. The problem occurs with the binary format with your version. I'll investigate on that, meanwhile you can still train model but only use the .tsv format model instead.

**Comment by jaseweston** [comment]
closing as no update for a while (can always reopen)

**Comment by pkmital** [comment]
@ledw I believe this happens because `ntokens_` is declared as a int32 but the read op tries to write into a int64.

**Comment by ledw** [comment]
@pkmital yes, I believe that is fixed in the current version.

**Comment by pkmital** [comment]
Absolutely right thank you!
