### ISSUE TITLE
Is there a way to get word vectors for bigrams at predict time?

### ISSUE THREAD

**Issue by rainjacket** [facebookresearch/StarSpace#43]
I don't fully understand the way Starspace / fasttext uses word ngrams.

**Comment by ledw** [comment]
@rainjacket  At predict time, word vectors for bigrams are automatically used, if you use -ngrams=2 in your model. However, we do not output word vectors for bigrams, as we use a hashing trick for bigrams and different bigrams may map to the same hashing key (for unigrams we keep a separate dictionary which does not using hashing function, so we have word vectors for each unigram in the dictionary).

**Comment by rainjacket** [comment]
@ledw thanks 👍 

I sort of understand that, but what if I'm happy to take the risk on ambiguous hashing? I don't need to enumerate all ngram vectors, only for individual input strings.

Same as how I assume the built-in method works at predict time. Or is there more I don't understand besides the hashing thing?

**Comment by ledw** [comment]
@rainjacket You're welcome. I think the hashing trick is the only thing you need to know. Do you think a function that does the following will be beneficial for you? A function that take input as a list of bigrams (or ngrams in general), and output the list of embedding vectors for those bigrams, according to the dictionary. Is that what you need? If so, I can add it.

**Comment by rainjacket** [comment]
@ledw That would be useful for me, I'd definitely vote in favor of that!

**Comment by matthias-samwald** [comment]
I think the ideal solution would be a general function that takes in strings (bi-grams, n-grams, sentences, documents) and works both 
 * in batch mode (i.e., reading and writing files) as well as 
 * interactively (i.e., through an interactive prompt -- this could also be used for creating Starspace wrappers from programming languages like Python).

Because currently it is not possible to use Starspace models with word n-grams in any applications, right?

**Comment by ledw** [comment]
@matthias-samwald Thanks for the suggestion. Currently if you use the test mode (./starspace test) and load a previously saved binary model then word n-grams are used. I think it's a good idea to have a separate function which output vectors for strings in batch / interactive mode. I'll update here again once that's implemented.

**Comment by ledw** [comment]
@rainjacket print ngrams vector is added in https://github.com/facebookresearch/StarSpace/commit/2aa4b8e451815a111b43fde782b0dafd0e5f3a76

To use, run the following command:
make print_ngrams
/print_ngrams <model> < ngrams.file

**Comment by spearsem** [comment]
@ledw I am unclear what is meant by a vector for a bigram in this setting. Will this just be the CBOW average of the word vectors for the constituent words of the bigram, or will it be a vector based on an embedding that knows how to embed bigrams as a single token directly? If it's the former, why not just request word vectors individually and create the average vector if you care about bigrams?
