### ISSUE TITLE
Gitter/Slack

### ISSUE THREAD

**Issue by ncammarata** [facebookresearch/Starspace#45]
Hi Jason & co! Would you be open to creating a room in some community platform for discussing Starspace in the open? I really like it's mission and would love to simply follow along with its development/thoughts and see how people are using it.

Nick

**Comment by jaseweston** [comment]
yes! we could do that -- which platform do you think is best?

**Comment by ncammarata** [comment]
Cool! I used to run a 500 person slack team for an open source project I worked on (github.com/motion/motion) and that was a pretty great user experience for everyone

**Comment by ncammarata** [comment]
I created a Workspace, which can be joined here

https://join.slack.com/t/fbstarspace/shared_invite/enQtMjQ3NDQ1MDQyMDY5LTY1YTJlYmQzZGE5OWRiZWUyZjE2ZTVmN2NmNWFmNTJlOTRhOTQ4MjI0NzVlMTA4NjBiMTAzYWFlZDI4ZTQxOTg

Looking forward to seeing you there!

**Comment by jaseweston** [comment]
We made a Facebook group instead as we know more how to use that ;)  https://www.facebook.com/groups/532005453808326
