### ISSUE TITLE
Is this model suitable for Chinese?

### ISSUE THREAD

**Issue by coderApes** [facebookresearch/Starspace#46]
My corpus is organized like docs in  wikipedia.  In an article, the sentence is divided by a tab character and  words are separated by a space bar.  I trained my model in trainmodel 3 , but when I test , it give infomation like following:
 
hit@1: 0 hit@10: 0 hit@20: 0 hit@50: 0 mean ranks : 7.42448e+06 Total examples : 1000

Dose this  means that my model is poor or these is somethingelse that maters? such as my corpus is organized  wrongly.

**Comment by jaseweston** [comment]
hmm, looks like a problem with the corpus... did you also provide basedocs for ranking using the metrics?

..there should be no problem with a different language.. did it build the dictionary ok and display how many things in the dictionary etc.? did the training look like the loss was going down?

**Comment by jaseweston** [comment]
closing, due to no reply...
