### ISSUE TITLE
Remove the Boost Lib Dependency

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/StarSpace#49]
Would it be possibile to remove the `boost` dependency? Is the `matrix.hpp` the only numeric library needed? If so, could be embedded.

By the way, I have upgraded `boost` on `macos`:

```
[loretoparisi@:mbploreto Starspace]$ brew upgrade boost
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
boost 1.65.1
==> Upgrading boost 
==> Downloading https://homebrew.bintray.com/bottles/boost-1.65.1.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring boost-1.65.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.65.1: 12,679 files, 401.1MB
```

and after setup `BOOST_DIR = /usr/local/Cellar/boost/1.65.1/` in the `makefile` I get:

```
In file included from src/proj.cpp:11:
In file included from src/proj.h:14:
src/matrix.h:26:10: fatal error: 'boost/numeric/ublas/matrix.hpp' file not found
#include <boost/numeric/ublas/matrix.hpp>
         ^
1 error generated.
make: *** [proj.o] Error 
```

**Comment by jaseweston** [comment]
We could do this as an extra option for people that need it,  but I guess it will be a bit slower...?

**Comment by loretoparisi** [comment]
@jaseweston well it would avoid those external libraries overhead that makes `fasttext` so easy to use on every kind of devices. So it would be a great option to use a different blas library / internal functions.

**Comment by jaseweston** [comment]
yes, got it, it's in our list

**Comment by alexott** [comment]
You can always embed the part of boost into source code by using `bcp` command from boost - it will disable the external dependency then

**Comment by loretoparisi** [comment]
@alexott do you mean while building starspace?

**Comment by loretoparisi** [comment]
... @alexott ok I see you mean building from boost source the `./bjam tools/bcp` that will generate the executable `bcp` and then extract only the sources referenced by starspace - and I assume its dependencies i.e. `boost/numeric/ublas/matrix.hpp` plus dependencies. I'm not sure how easy is doing this when dealing with multiple platforms.

**Comment by alexott** [comment]
`bcp` will copy all necessary dependencies, including support for multiple platforms.

**Comment by alexott** [comment]
ok, from what I see - besides ublas, other libraries are used such as, string_algorithm, archive, etc.  And they have quite big dependencies on other modules, so it makes no sense to copy everything into source tree.

**Comment by ledw** [comment]
We do not plan to remove the boost dependency at this point. Closing the issue.

**Comment by loretoparisi** [comment]
@ledw okay, and since boost is used as the blas library, what about gpu support?
