### ISSUE TITLE
Example for PageSpace user / page embeddings

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/StarSpace#50]
Could you please provide an example script with sample (anonymized of course) data of the `PageSpace user / page embeddings` in order to test the recommendations task.

**Comment by jaseweston** [comment]
We can't put this data up, sorry, it's not public.
We could give an example from MovieLens or something, but it's a bit different task (not content-based), and we haven't tried anything on that yet..

**Comment by loretoparisi** [comment]
@jaseweston thanks. Could it work for session based recommender task like [RecSyS 2105](http://2015.recsyschallenge.com/challenge.html) This task's dataset is free and ready to use. Also in the next weeks the [RecSys 2018](https://recsys.acm.org/recsys18/challenge/) will release a new public dataset fo recommendations

**Comment by jaseweston** [comment]
It will certainly work, yes..  it's on our list

**Comment by loretoparisi** [comment]
@jaseweston pretty amazing, can't wait to work with it. Question: what changes in spaceship training method when doing content-based recommendation rather than session based (i.e. the item id)?

**Comment by jaseweston** [comment]
This is explained in the paper, see page 2, bottom right
https://arxiv.org/pdf/1709.03856.pdf

**Comment by loretoparisi** [comment]
Hello @jaseweston any update on these examples? Thank you!

**Comment by jaseweston** [comment]
Sorry, still on our list to do, we have added extra scripts for sentence and article learning though since we last spoke, and more details in the README. But this one is still missing..

**Comment by XiaolinZHONG** [comment]
hi  @jaseweston ,i am new to starspace and i use starspace as follows:
input file type: 
`userid_1 shopid_1234 shopid_2345 shopid_3456`
use command: 
`$./starspace train -trainFile input.txt -model pagespace -label 'shopid_' -trainMode 1`
then i get the tsv file as ：
```
SHOPID_123	-0.00749861	0.00552596	-0.00345658	0.00619185	0.0231832	-0.0145031	-0.00503505	0.01161	-0.000706066	0.00559112
SHOPID_234	0.000454705	-0.00207393	0.00260599	-0.0135882	-0.0178325	-0.00605847	-0.0138976	0.00337469	-0.0139814	0.00115129

```
if i want get the user vector ,should i sum all the shops' vector ?  and recall candidate shop with cosine similarity ?

**Comment by ledw** [comment]
@XiaolinZHONG Yes, summing all the shops' vector is the way to correct way to do. If you used cosine similarity for training, then you should use it at serving time as well.

**Comment by jaseweston** [comment]
Yes, you should also be able to use the utility "query_predict" (described
at the bottom of the README) to do this as well?

**Comment by XiaolinZHONG** [comment]
hi @ledw  the example above may be a bit of a problem, and now I'm running a new data and the result is this:
THE INPUT FILE: input.txt
`userid_1 shopid_1234 shopid_2345 shopid_3456
  userid_2 shopid_234 shopid_345 shopid_346
`
USE COMMAND : 
`$./starspace train -trainFile input.txt -model TESTMODEL -label 'shopid_' -trainMode 1`
THEN I GET THE TSV FILE:
`userid_1  0.00089133	0.000230685	-0.00248654	0.000365109	0.000890341	-0.000866873	0.000125772	-0.000854835	0.00128995	0.000342647
userid_2   0.00327629	0.000613278	-0.0061509	-0.00450719	0.00523581	-0.000884475	-0.001786	0.00261733	0.00446325	-0.00119397

`
Obviously this is the userid's vector.
i want to know how could i get the shopid's vector ?
like this `shopid_234 0.000454705	-0.00207393	0.00260599	-0.0135882	-0.0178325	-0.00605847	-0.0138976	0.00337469	-0.0139814	0.00115129`

**Comment by ledw** [comment]
@XiaolinZHONG the .tsv file should give you both userid and shopid vectors. The shopid vectors should be stored at the end of the .tsv file. Can you check that? Thanks.

**Comment by XiaolinZHONG** [comment]
@ledw yes,it's my fault。thanks your kindly help。

**Comment by XiaolinZHONG** [comment]
Hi! @ledw  Sorry to bother you again,Recently,I am using Starspace (trainMode 1) to recommendate some pages to users, but I am confused by the result.
can you give me some tips about how to use this tool correctly?

Follows are the details about my operation:

A. PREPARE THE TRAIN SAMPLES 
The train data is fasttext fileFormat like this:

```
USERID_1 SHOPID_123 SHOPID_234 SHOPID_345 SHOPID_456 ...
USERID_2 SHOPID_342 SHOPID_123 SHOPID_356 SHOPID_345 ...
...
```
The whole file have 29021194 non-duplicate samples. And the SHOPID_XXX is USERID_XXX has clicked in past.

B. USE THE STAR_SPACE TO TRAIN THE MODEL 

I use the StarSpace by follows command:

`./starspace train -trainFile my_train_data.txt -model my_page_space -label 'SHOPID_' -trainMode 1 -dim 100 -thread 20`

Then I get the following data :
```

Arguments: 
lr: 0.01
dim: 100
epoch: 5
maxTrainTime: 8640000
saveEveryEpoch: 0
loss: hinge
margin: 0.05
similarity: cosine
maxNegSamples: 10
negSearchLimit: 50
thread: 20
minCount: 1
minCountLabel: 1
label: SHOPID_
ngrams: 1
bucket: 2000000
adagrad: 1
trainMode: 1
fileFormat: fastText
normalizeText: 0
dropoutLHS: 0
dropoutRHS: 0
Start to initialize starspace model.
Build dict from input file : my_train_data.txt
Read 912M words
Number of words in dictionary:  2201447       **<-------- ? I dot understand what's does it mean ? does it represent the USERID numbers ? if it does, why does it less than my USERID number? **
Number of labels in dictionary: 6523787       **<--------  ？The labels numbers is less than my non-duplicate SHOPID numbers.**
Loading data from file : my_train_data.txt
Total number of examples loaded : 26292532    **<-------- ？ While this samples number is not equal to my sample numbers.**
Training epoch 0: 0.01 0.002
Epoch: 100.0%  lr: 0.007998  loss: 0.006335  eta: 2h34m  tot: 0h38m35s  (20.0%)
 ---+++                Epoch    0 Train error : 0.00635667 +++--- ☃
Training epoch 1: 0.008 0.002
Epoch: 100.0%  lr: 0.006026  loss: 0.003578  eta: 1h59m  tot: 1h18m53s  (40.0%)
 ---+++                Epoch    1 Train error : 0.00357852 +++--- ☃
Training epoch 2: 0.006 0.002
Epoch: 100.0%  lr: 0.004007  loss: 0.003039  eta: 1h20m  tot: 2h0m8s  (60.0%))
 ---+++                Epoch    2 Train error : 0.00303532 +++--- ☃
Training epoch 3: 0.004 0.002
Epoch: 100.0%  lr: 0.001999  loss: 0.002786  eta: 0h40m  tot: 2h41m18s  (80.0%)
 ---+++                Epoch    3 Train error : 0.00279179 +++--- ☃
Training epoch 4: 0.002 0.002
Epoch: 100.0%  lr: 0.000001  loss: 0.002672  eta: <1min   tot: 3h22m18s  (100.0%)
 ---+++                Epoch    4 Train error : 0.00267963 +++--- ☃
Saving model to file : my_page_space
Saving model in tsv format : my_page_space.tsv
```

C. FOLLOWS ARE MY RESULT
When I open the my_page_space.tsv, I get this :
```
USERID_755195555	0.00089133	0.000230685	-0.00248654	0.000365109	0.000890341	-0.000866873	0.000125772	-0.000854835	0.00128995	0.000342647	0.000328219	0.00257582	-0.000627516	-0.00172174	0.000282489	0.000737613	0.000202373	-0.00018954	-0.000274135	0.000541478	-0.000131711	0.000673161	0.000151625	-0.00195011	0.00130916	-0.000472415	0.000443215	0.0018935	-0.000832299	0.000189262	-0.00122573	0.00198107	0.00110598	0.000319197	0.00155543	-4.34281e-05	0.000696329	-0.000686457	0.00126298	0.00186231	-0.000868199	0.00111783	-0.0020383	-0.00141629	-0.00118842	0.000272488	-0.0010397	0.00124978	-0.000795619	-8.30151e-05	-0.000148639	-0.000169522	-0.000523787	-6.59093e-05	-0.00327348	0.000418244	0.00178561	0.000810348	-0.000374892	0.00113165	-0.000448247	-0.000414134	0.00151381	0.00107189	0.0013608	0.00176947	-0.000458166	-0.000652871	0.000406676	0.00130658	-0.000296783	0.000515681	-0.000635848	-0.000836783	-0.000824591	-0.000211483	0.00128125	0.00143133	-0.000581245	5.16391e-05	0.00167437	0.00035592	-0.002933	-0.00131379	0.000335282	-0.0013781	0.000249108	-0.000917136	0.000526941	-0.000877861	0.000762403	-0.00118499	0.00132287	-0.000705656	0.00117128	-0.000384351	0.00156441	0.000392377	-0.00109356	0.00116393
USERID_755215647	0.000127128	0.0012827	-0.000505943	0.000402534	0.00135071	0.000393898	0.000646368	0.000622771	-0.000180522	2.65165e-05	3.49648e-05	-0.00120718	-0.000789293	0.00100895	0.00122282	0.00207037	1.45202e-05	0.00120798	-0.000262871	0.000569295	-0.000275136	-0.0014859	-0.00153771	0.000890536	0.000707041	-0.0006182	0.000309299	-4.0692e-05	-0.000536503	0.000136005	-0.000472754	0.000620671	-0.000943211	0.000124694	4.99193e-05	0.000644262	8.8238e-05	-0.00132408	-0.000483307	0.000952875	-0.00185922	-0.00061064	0.000654592	-0.0008266	0.000440958	-0.000134132	0.00019044	0.000996724	-0.00103499	-0.000727467	-0.000365538	0.00123581	0.000325673	0.000990261	-0.000231153	8.30489e-05	0.00128275	6.60238e-05	0.000450591	0.000262489	-0.000735527	0.000550965	0.000679567	-0.00183378	-0.000516485	-0.000978698	-0.00104051	0.00163151	-0.000234532	-0.00164381	-0.00119211	-0.000417175	-0.00165001	0.000315992	0.00056259	0.00136455	-0.000491353	0.000516529	-0.0011056	-0.000201602	0.00124066	-0.00120764	-0.000833541	-0.000478907	-0.000185696	-0.0016375	-0.00105251	-0.000858633	0.00106081	-0.00107401	-0.00076893	-3.78957e-05	-0.000372352	-0.00156803	-0.00244932	-0.00018024	-0.00104117	-0.000830985	-0.000602306	0.00215305
...
SHOPID_59109939	0.0176825	0.0139031	-0.0128432	0.0131765	0.0193838	-0.0186899	0.00533668	-0.0162892	-0.00953157	0.0155102	-0.019133	0.00166827	0.0122249	-0.0137382	-0.0155917	-0.00155115	-0.000483634	0.0119736	-0.0109989	-0.00115437	0.00893294	-0.00990738	0.0155781	-0.00997385	0.0324434	-0.00392773	-0.0118932	-0.0219689	-0.0143011	0.0160589	0.0133995	0.00872258	-0.00301728	0.00899072	0.00145527	0.00619002	0.00235113	-0.0308634	-0.00482099	0.0210877	0.0130199	-0.010816	0.014129	0.00576521	0.0034162	-0.00597463	0.00830461	-0.0325854	-0.0151248	-0.00080951	-0.013705	0.0252776	-0.0293351	-0.0249686	-0.002303	-0.00323098	-0.00649529	0.000843153	0.0105828	-0.00925347	-0.00729652	-0.00356907	-0.000108399	0.00464031	-0.0102219	0.000357127	-0.0184474	0.0223842	0.00471359	-0.0114364	-0.0181597	-0.00373681	-0.0126361	-0.0141793	-0.0140869	0.00209912	-0.000455034	0.0110556	0.00168038	-0.011601	0.0166562	-0.011906	0.0341672	-0.0185097	0.00787438	0.00330727	-0.0089975	-0.00667935	0.00063956	-0.0015916	-0.012258	-0.00292932	0.00258045	-0.0131476	-0.0127332	0.00520907	0.00992678	-0.0231683	0.0119097	0.000726623
SHOPID_5246741	0.0192595	0.0091392	-0.015553	0.00895552	-0.0158271	-0.0073582	0.000703409	-0.00724248	0.00455534	-0.00861478	0.0260805	0.0138632	0.00982043	0.0064851	-0.00437661	0.021635	-0.0140449	0.00523301	-0.0230957	0.000288472	0.0050056	-0.00671393	0.00564734	-0.0195474	-0.00130446	0.00720213	-0.0133131	-0.00739021	0.0103506	0.0217146	0.00913162	0.017011-0.0162439	0.0300447	0.0321563	0.0201797	0.0124638	-0.0135183	0.0118939	0.00262768	-0.000885183	-0.00276957	-0.0229422	0.0309603	0.0226949	-0.00485187	-0.0128974	0.0178249	0.00128254	1.34875e-05	0.0114059	0.0276746	0.00365342	0.0223029	-0.0068409	-0.031346	-0.0104785	-0.00416829	0.0191272	-0.0221677	0.0166308	-0.00360035	-3.21595e-05	0.0221879	0.00178137	-0.0174953	0.00828367	-0.00976834	0.0284731	-0.00556861	-0.000342531	0.00947691	0.0208702	0.00260648	0.0042999	0.00990656	-0.012028	-0.0257626	-0.0210129	0.00767296	0.000626189	0.00792703	-0.0202655	0.00851135	0.0249406	0.00552526	-0.0198208	-0.0208169	0.0282808	0.00783498	-0.014803	0.00653915	-0.00872747	0.00113735	0.0286251	0.0359677	0.0244788	0.0104167	-0.0183842	0.00486486

```
The above part is the USERID's vector, the below part is the SHOPID's vector, and sperated by tap.

What I am confused are:

1. Why does the model get a less number of samples? Why some of the USERID can't be found in the result file (my_page_space.tsv).
2. The USERID_XXX's vector does not seem to be the sum of the SHOPID_XXX's vectors that the user has clicked ? 
   Should I sum all the SHOPID_XXX's vector accorrding to the USERID_XXX's click to get the real USERID's vector, not by using USERID_XXX's vector in my_page_space.tsv directly ?
3. Could you give us some more detail user guide examples for newer ?

**Comment by ledw** [comment]
@XiaolinZHONG Hi, thank you for providing the details in your questions. Regarding your questions:
1. The dictionary used in the model has a cap on total number of word/labels. If the total number of user_id and shop_id is too big, it automatically increases the threshold for minCount and minCountLabel to avoid OOM. I suggest you to set minCount and minCountLabel > 1 to filter out infrequent features, but if you want to keep everything, try to increase MAX_VOCAB_SIZE in the dictonary (as long as memory can hold): https://github.com/facebookresearch/StarSpace/blob/master/src/dict.h#L66
2. No, if you put the user_id explicitly in the examples, then it will be trained directly, rather than being the sum of the shop_ids. Yes, you should sum all the shop_ids' vector according to the user_id's vector. In addition, you can remove the user_ids in the training file so they will not be trained (your model.tsv will only contain shop_ids, and you use that to represent user_id).
3. Yes, I think we should provide better examples/guide for this use-case. We're working on that and will keep you updated.
Feel free to ask us more questions if anything's not clear.

**Comment by XiaolinZHONG** [comment]
@ledw Great! Thanks for your help !

**Comment by loretoparisi** [comment]
@ledw 💯 thanks a lot, I will evaluate it.

**Comment by davidalbertonogueira** [comment]
Can you provide an example of StarSpace tackling content-based recommendation? 
i.e., how should the files be formatted and what are the necessary command line arguments to run it.
