### ISSUE TITLE
Feature Request: Training mode Docs Improvements

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/StarSpace#54]
Considering that `Starspace` has several training modes, it solves different tasks, and has different dataset file formats and models type to deal with, I have tried to summarize/recap everything in the google sheet [here](https://docs.google.com/spreadsheets/d/1SqgW9ylb36oBWOU1Cul0QCbRG9nuaru-rhsh6-moKOg/edit?usp=sharing)

This table looks like the following

<img width="1202" alt="schermata 2017-09-28 alle 18 01 22" src="https://user-images.githubusercontent.com/163333/30977204-20c9b826-a477-11e7-9369-b2369d5aefcb.png">

Of course there could be errors due to my understanding, but something like this could help a lot to choose the right model/dataset/training mode.

Hopefully it helps!

**Comment by jaseweston** [comment]
thanks! our plan here is just to improve our README, we are in the process of adding more code examples and clearer descriptions ..

**Comment by loretoparisi** [comment]
@jaseweston thank you, so closing this!
