### ISSUE TITLE
Crashing makefile

### ISSUE THREAD

**Issue by RedShift51** [facebookresearch/StarSpace#55]
Good day, i followed your instructions to build the model, but i had a problem in the "make" line, after git clone and cd Starspace:

makefile:84: recipe for target 'data.o' failed
make: *** [data.o] Error 1

I use Ubuntu 16.04 LTS, 
How can i solve this problem?
Thank you

**Comment by loretoparisi** [comment]
@RedShift51 Did you installed the `boost` lib? You have to

```
$wget https://dl.bintray.com/boostorg/release/1.63.0/source/boost_1_63_0.zip
$unzip boost_1_63_0.zip
$sudo mv boost_1_63_0 /usr/local/bin
```

before

```
git clone https://github.com/facebookresearch/Starspace.git
cd Starspace
make
```

**Comment by ledw** [comment]
@RedShift51 does the solution suggested by @loretoparisi works for you?

**Comment by jaseweston** [comment]
Closing because no reply to @ledw, assuming it's all good
