### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by apiro** [facebookresearch/StarSpace#65]
This issue is thrown when I compile Starspace with a macos having a g++:
- Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

The trace of the error is:
MacBook-Pro-di-Alberto:StarSpace albertomariopirovano$ make
g++ -pthread -std=gnu++11 -O3 -funroll-loops -g -c src/data.cpp -o data.o
In file included from src/data.cpp:12:
src/utils/utils.h:138:42: error: variable 'partitions' with variably modified type cannot be captured in a lambda expression
    threads.emplace_back([i, f, &fname, &partitions] {
                                         ^
src/utils/utils.h:120:9: note: 'partitions' declared here
  off_t partitions[numThreads + 1];
        ^
src/utils/utils.h:142:18: error: variable 'partitions' with variably modified type cannot be captured in a lambda expression
      ifs2.seekg(partitions[i]);
                 ^
src/utils/utils.h:120:9: note: 'partitions' declared here
  off_t partitions[numThreads + 1];
        ^
src/utils/utils.h:144:28: error: variable 'partitions' with variably modified type cannot be captured in a lambda expression
      while (tellg(ifs2) < partitions[i + 1] && getline(ifs2, line)) {
                           ^
src/utils/utils.h:120:9: note: 'partitions' declared here
  off_t partitions[numThreads + 1];
        ^
src/utils/utils.h:142:18: error: variable 'partitions' with variably modified type cannot be captured in a lambda expression
      ifs2.seekg(partitions[i]);
                 ^
src/data.cpp:42:3: note: in instantiation of function template specialization 'starspace::foreach_line<std::__1::basic_string<char>,
      (lambda at src/data.cpp:44:5)>' requested here
  foreach_line(
  ^
src/utils/utils.h:120:9: note: 'partitions' declared here
  off_t partitions[numThreads + 1];
        ^
src/utils/utils.h:144:28: error: variable 'partitions' with variably modified type cannot be captured in a lambda expression
      while (tellg(ifs2) < partitions[i + 1] && getline(ifs2, line)) {
                           ^
src/utils/utils.h:120:9: note: 'partitions' declared here
  off_t partitions[numThreads + 1];
        ^
5 errors generated.
make: *** [data.o] Error 1

What is the error about?

**Comment by ledw** [comment]
@apiro it should be fixed in f47a831ff007f9c5f005ae379341122db3340787
could you try again?

**Comment by apiro** [comment]
@ledw There was the same statement at line 680 of src/model.cpp, so after applying there the same correction the make command worked. 
Thank you !
