### ISSUE TITLE
Script used for preprocessing Wikipedia data

### ISSUE THREAD

**Issue by pkmital** [facebookresearch/StarSpace#67]
Thanks for a great release!  I am wondering if you can open source the code used to preprocess the wikipedia data into `wikipedia_shuf_train5M.txt`?  I'd like to as closely replicate it on a novel dataset and use it alongside the wikipedia data if possible.

**Comment by ledw** [comment]
@pkmital apologize for the delay in replying. We'll look into providing the preprocessing code and update you shortly.

**Comment by ledw** [comment]
@pkmital Our script for preprocessing the wikipedia data into `wikipedia_shuf_train5M.txt ` is mainly based on the [WikiExtractor](https://github.com/attardi/wikiextractor). 
Could you take a look and see if that provides what you need to replicate it on the novel dataset?

**Comment by jaseweston** [comment]
Closing because no reply.
