### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by AwkwardBoy** [facebookresearch/StarSpace#68]
I train a model use my own data with labels in a short time, but when I use the model to test, there was no response, it showed have loaded the test file and model, I wait for a relative long time but nothing happened, even raised any error.

**Comment by ledw** [comment]
@AwkwardBoy could you share the commands you ran and some example data? That way we can reproduce the bug and figure out what went wrong. Thanks!

**Comment by AwkwardBoy** [comment]
Sorry, it seems that I used a relative large test data to the model, and it use a pretty long time than my image. I used a small test data, and it works well. Many thanks

**Comment by ledw** [comment]
@AwkwardBoy thanks for the update. You can also set -thread to a larger number (default is 10) for bigger datasets. Closing the issue for now.
