### ISSUE TITLE
Building problem from Jupyter notebook: "make: Nothing to be done for 'opt'. "

### ISSUE THREAD

**Issue by ben0it8** [facebookresearch/StarSpace#71]
Hello,

I'm trying to build StarSpace in a Jupyter Notebook with:
```
%%bash
cd Starspace
make

``` 
and I get:

> make: Nothing to be done for 'opt'.

If I tabulate after opt, I also get some errors.
Any idea what could be done?

**Comment by NeelKanwal** [comment]
I have same kind of issue ti show problem
