### ISSUE TITLE
Confusing parameters when calling ./starspace train

### ISSUE THREAD

**Issue by ben0it8** [facebookresearch/StarSpace#72]
Hello,

I pass -normalizeText 1 and -adagrad 1 to ./starspace train, but in the list of arguments on the stdout, they tend to show values 0 and 0 respectively.
Do you have any idea what could be the reason why the args change?

Thanks,
Oliver

**Comment by ledw** [comment]
@ben0it8 Hi Oliver, the -noramlizeText and -adagrad are of boolean values, so you need to pass -normalizeText true and -adagrad true.

**Comment by ledw** [comment]
@ben0it8 we improved the parsing for arguments in https://github.com/facebookresearch/StarSpace/commit/6da65f259319d5662b0bc92bba02cc7505d17b70. 
Now you should be able to pass -adagrad 1.
Closing the task.
