### ISSUE TITLE
Link broken for Freebase15k dataset

### ISSUE THREAD

**Issue by jrieke** [facebookresearch/StarSpace#74]
It seems like the server for the Freebase15k dataset is down (this link: `https://everest.hds.utc.fr/lib/exe/fetch.php?media=en:fb15k.tgz` in the `examples/multi_relation_example.sh` script). Could you fix this or provide an alternative download source?

Thanks, Johannes

cc @ben0it8

**Comment by ledw** [comment]
@jrieke you can download the data at the following source:
https://github.com/mana-ysh/knowledge-graph-embeddings/blob/master/dat/fb15k.tgz

We'll change our script as well.

**Comment by ledw** [comment]
@jrieke It's updated in https://github.com/facebookresearch/StarSpace/commit/168910e3215d12b56fe814d059661d10d4ed3e4b.

Closing the issue now.

**Comment by jrieke** [comment]
Perfect, thank you!
