### ISSUE TITLE
Assertion `id < size_' failed in dict.cpp when using ngrams > 1 in test

### ISSUE THREAD

**Issue by ben0it8** [facebookresearch/StarSpace#79]
In case I train with trainMode = 0 and ngrams > 1, during the test call I get the following error:

> starspace: src/dict.cpp:59: const string& starspace::Dictionary::getSymbol(int32_t) const: Assertion `id < size_' failed.
> Evaluation Metrics :
> hit@1: 0.336957 hit@10: 0.5 hit@20: 0.641304 hit@50: 0.826087 mean ranks : 28.1957 Total examples : 92
> Aborted
 
This results in an empty predictionFile.

**Comment by ledw** [comment]
@ben0it8 fixed now in https://github.com/facebookresearch/StarSpace/commit/e180b8c5eb91572022287dfd7d47fa22f0d4dce4. Thanks!
