### ISSUE TITLE
hit@1: 0.545086 hit@10: 0.956689 hit@20: 0.990893 hit@50: 1 mean ranks : 2.77 Total examples : 27891

### ISSUE THREAD

**Issue by civis** [facebookresearch/StarSpace#81]
how to explain my test output：hit@1: 0.545086 hit@10: 0.956689 hit@20: 0.990893 hit@50: 1 mean ranks : 2.77 Total examples : 27891。 I dont understand “hits@1 metric”， could you give me some information about it？

**Comment by kdqzzxxcc** [comment]
@civis hit@n is the same as top@n in classification.
you can check [this](https://stackoverflow.com/questions/37668902/evaluation-calculate-top-n-accuracy-top-1-and-top-5) for some details.

**Comment by ledw** [comment]
@civis yes hit@1 means the top 1 accuracy: the fraction of test examples that the model's first prediction is the correct answer.

**Comment by jingsliu** [comment]
@ledw I noticed in the script that the evaluation is only for single-class prediction. How shall I interpret the values for multi-label models?
Thanks

**Comment by jaseweston** [comment]
The evaluation assumes only one left out positive label is being ranked amongst many other assumed negative labels, and we measure hits@k.   We could definitely generalize this to multiple positive test labels, it is straight-forward, but not in the code yet..

**Comment by jingsliu** [comment]
Thanks for the response, just to clarify, you mean **the first label** following each sample is used to as the positive case evaluate the performance?

**Comment by jaseweston** [comment]
I think it is a random positive out of the set right @ledw ? -- and it depends on which trainmode you are in -- it will extract a positive example using the particular type of trainmode, see the top level README.

**Comment by ledw** [comment]
@jingsliu yes @jaseweston's explanation is correct.

**Comment by DinaS18** [comment]
@ledw could you please explain the mean ranks metric? What is the correct interpretation of it? Thank you
