### ISSUE TITLE
how to embed document space 

### ISSUE THREAD

**Issue by KazuakiAihara** [facebookresearch/StarSpace#84]
Could you please provide an advice how to embed document space like Doc2vec.
I want to embed document space and make sure which document is most similar to one document.
I trained my textdata formatted by fasttext. So can I use trained model like a Doc2vec model?
( xxxxxx.mostsimilar(["I like dog"]))

**Comment by ledw** [comment]
@KazuakiAihara you can obtain document vector by averaging all the word vectors for words in the dictionary, from a trained word embedding model. Currently we do not have an option to print out sentence / document vector, but we will add that soon. Does that answer what you asked for?

**Comment by jaseweston** [comment]
Yes, and those embeddings should be obtained by training something like ArticleSpace, as in the README.

**Comment by dhmay** [comment]
I'm interested in a feature to print the embedding of a file of inputs, as well, in the -useWeight context. 

In that context, what is the method for obtaining the document vector? Does one average all the word vectors, with each word vector weighted by the input value for that word?

**Comment by jaseweston** [comment]
Yes, it is weighted something like that, right @ledw ?

**Comment by ledw** [comment]
@dhmay yes that is the expected behavior in the weighted case.

**Comment by ledw** [comment]
@KazuakiAihara @dhmay The feature for printing of a file of inputs is added. To use that, run
`make embed_doc`
`./embed_doc <model> [filename]`
if filename is not provided, it will read from stdin line by line

**Comment by dhmay** [comment]
There's a trivial typo in embed_doc.cpp. When I try to make embed_doc, I get this:

$ make embed_doc
g++ -pthread -std=gnu++11 normalize.o dict.o args.o proj.o parser.o data.o model.o starspace.o doc_parser.o doc_data.o utils.o -I/usr/local/bin/boost_1_63_0/ -g src/apps/embed_doc.cpp -o embed_doc
src/apps/embed_doc.cpp:19:1: error: ‘voiid’ does not name a type
 voiid embedDoc(StarSpace& sp, istream& fin) {
 ^
src/apps/embed_doc.cpp: In function ‘int main(int, char**)’:
src/apps/embed_doc.cpp:56:21: error: ‘embedDoc’ was not declared in this scope
     embedDoc(sp, fin);
                     ^
src/apps/embed_doc.cpp:60:21: error: ‘embedDoc’ was not declared in this scope
     embedDoc(sp, cin);
                     ^
make: *** [embed_doc] Error 1

Changing "voiid" to "void" clears it up.

**Comment by ledw** [comment]
@dhmay thanks for reporting. fixed now.

**Comment by KazuakiAihara** [comment]
ledw
Thank you for adding embed_doc.
