### ISSUE TITLE
'Assertion `example.RHSTokens.size() > 1' failed' at test time and trainMode = 5

### ISSUE THREAD

**Issue by ben0it8** [facebookresearch/StarSpace#86]
hello,

whenever testing with trainMode = 5 on an unlabelled corpus with default parameters, I get the following error in void InternDataHandler::convert():

> starspace: src/data.cpp:90: virtual void starspace::InternDataHandler::convert(const starspace::ParseResults&, starspace::ParseResults&) const: Assertion `example.RHSTokens.size() > 1' failed.
> Aborted
>

as a result, there's no predictionFile output.

**Comment by ledw** [comment]
@ben0it8 the test mode is not defined for trainMode 5 unfortunately. What do you want to test about trainMode 5 (word level training)? 
For instance, if you want to check the quality of the word embeddings trained by trainMode 5, you can query the nearest neighbors for trained word embeddings, like the following:
`make query_nn';
'./query_nn <model> [k]`

**Comment by ledw** [comment]
@ben0it8 proper error handling for trainMode 5 in testing. Closing the issue now.
