### ISSUE TITLE
Install error: cblas.h file not found

### ISSUE THREAD

**Issue by jingsliu** [facebookresearch/StarSpace#87]
Hi I'm having installation error with the most recent update (didn't happen before). Getting the error message below:

In file included from src/proj.cpp:11:
src/proj.h:22:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^
1 error generated.
make: *** [proj.o] Error 1

**Comment by ledw** [comment]
@jingsliu thanks for reporting. Removed it in https://github.com/facebookresearch/StarSpace/commit/08b1460636c4a27d3f560f0250ffe9bada0c7ed4 as it was unnecessary.
