### ISSUE TITLE
per-epoch models files overwrite each other

### ISSUE THREAD

**Issue by dhmay** [facebookresearch/StarSpace#95]
With the -saveEveryEpoch argument, the model file specified in -model gets saved after every epoch, so that each per-epoch model overwrites the last. I'd like to have all of those per-epoch models available when training is done, for running on validation data and picking the best epoch. Would it be possible to (maybe optionally) save those files to, e.g., model.1, model.2, model.3...?

**Comment by jaseweston** [comment]
yes we might not want that as default as it takes disk space.. but could be an option...?

**Comment by ledw** [comment]
@dhmay @jaseweston yes we can add that as an option.

**Comment by ledw** [comment]
@dhmay included in https://github.com/facebookresearch/StarSpace/commit/d753a529fe97db7a40bfcd565127fd9f37ed6e33.
