### ISSUE TITLE
Add weight importance to file format

### ISSUE THREAD

**Issue by pommedeterresautee** [facebookresearch/StarSpace#99]
In many cases, it makes sense to say that an observation is more important than another one.
Right now, there is no obvious way to provide this information.
Would it be possible to add such feature?
It would look like an optional key word to add to each sample (for instance `__weight__:2.5`).
The effect would be to increase the loss (and the correction) for that sample.

What do you think?

**Comment by jaseweston** [comment]
Yes, it is possible to add, but I am not sure we intend to support this right now (option overload) unless many people request it.
Note that you could also do this right now by replicating examples in the training file corresponding to their weight (but it's a bit of a pain and waste of memory, but still, you can).

**Comment by pommedeterresautee** [comment]
I am not sure it would be the same (2 times a loss is not the same than seeing the same observation 2 times, because the second time a first correction has been applied).
Few would request it if you don t explain in the examples how to concretely use it (as you did with train modes). For instance content recommendation may take the price into account (or just a log of the price), sentence similarity applied to query suggestion (I have tried and it works much more than graph approach FYI) would take the interaction into account (download of a content should count more than just opening a document, or may be the dwell time would make a nice weight), for classification the use of weight would be obvious, etc.
Really I can't think of any basic function that would be missing (compared to Vowpal for instance).

Would it be complex to add?

**Comment by ledw** [comment]
@pommedeterresautee Thanks for the suggestion. We'll set the default setting of normalizeText to false (in most cases it's just lower casing, see details in src/utils/normalize.cpp 

We'll add the weighted example case in our list of features to implement.

**Comment by pommedeterresautee** [comment]
@ledw I was thinking that to improve results of sentence similarity, it may help to provide myself some specific negative examples (instead of random ones) and realised that a negative weight may do the trick... May be you want to add that usecase in some way in your examples when weighting will be implemented.

**Comment by ledw** [comment]
@pommedeterresautee support for weighted examples added in https://github.com/facebookresearch/StarSpace/commit/57c6212e89be5789487fbb96e860f5193ecad7fc.

The weighted examples needs to be in the following format:
`__weight__:xxx <tab> ...word_1 <tab> ... <tab> label_1`
Note that it needs to have prefix `__weight__` followed by ':' and the weight value. The weight block needs to appear first in the line that contains one example.

**Comment by pommedeterresautee** [comment]
Thanks a lot for this feature!!
I have started to read the source code but I am still not sure to understand how it works, in particular how I may have several weights on one line where there are several examples on the line.
Imagine I want to learn sentence similarities where sentence are queries.
Some queries in a session are more important than others from the same session, so I want to make them more "attractive" than the others by increasing the loss attached to it. In some way they will attract the other queries to them. From my understanding I can have only one weight by line so there is still no way for me to attach a weight per query. Am I right?

To illustrate my question can I do :
`__weight__:0.1 query_1_word_1 query_1_word_2 query_1_word_3 <tab> __weight__:0.9 query_2_word_1 query_2_word_2 <tab>__weight__:0.5 query_3_word_1 query_3_word_2 query_3_word_3` ?

**Comment by ledw** [comment]
@pommedeterresautee You're welcome! Your understanding is correct: the weight is added on the example level, and not doc level. The reason being that with different trainModes, it becomes complicated to add weights on doc level. I would suggest that, in your use case, to explode your examples into multiple examples, each containing different weight. 
If you're unclear about what I meant by 'explode', please share with me your script and sample data, and I can see if we can reduce that to cases that can be handled by having weights at example level.

**Comment by pommedeterresautee** [comment]
I was thinking to this solution too but to reproduce this way of working it means that if in a session I have for instance 40 queries, I need to generate 40 * 39 = 1560 pairs of queries. This may lead to really really big file and require a change in the way train files are created (so far everything is in Ram on a big server with lots of Ram). I have not yet tried but it s even possible it will require to sub-sample the dataset because of the hard drive limit.
When examples are separated by a tab character, in which train mode there is a difficulty to put a weight per block of text?
In particular, with labelDoc format, it would mean that the weight can be put everywhere, isn't it?

It seems that putting the weight per example make sense for almost all trainmodes:

- `trainmode 0` : when there is no labelDoc format, the weight is for the whole example (so if there are several labels, the weight is applied to all of them), when there is labeldoc the weight is put with the label so the weight depends of the label. There is still the question what to do if the weight is put in the example itself and the label block? Need to add the weight? May be complex for nothing.
- `trainmode 1` : when there is no labeldoc format the weight is the same for all examples, and if labeldoc is activated you can have a weight per example.
- `trainmode 2` : same as trainmode 1
- `trainmode 3` : always several block of texts, so always one weight per example
- `trainmode 4` : as said before trainmode 4 is just trainmode 3 with a weight of 0 on one of the example
- `trainmode 5` : there is only one text block per line (tab character has no meaning in this trainmode), so the weight will be applied to the whole sentence (as it is the case with the feature right now).

**Comment by pommedeterresautee** [comment]
@jaseweston @ledw hi, is there another way to achieve the same results without generating huge file?

**Comment by jaseweston** [comment]
@ledw  -- can we reconsider this?

**Comment by ledw** [comment]
@pommedeterresautee Thanks for the suggestions. Apologize for the delay in replying. For integrating different weights for sentence in different trainMode, I have two questions:
1. For instance, in trainMode 1, we use sentence weight and word weight for each word, so in a combined document representation, each word would have the weight sum(sentence_weight * word_weight_in_sentence)?
2. In negative sampling: currently we do negative sampling by taking a random sentence from an example (i.e. trainMode 1, 3), in those cases, should the negatives use the sentence weight or not?

**Comment by pommedeterresautee** [comment]
If I understand you correctly, you are wondering what to do when you have a global weight for the example and a weight for a word (in trainmode 3 for instance)?
If my understanding is correct, IMO, you shouldn't have both weights at the same time. Otherwise, it would be complex for the user and not very useful, plus how would we recognize that it s a sentence weight or the weight of the first sequence/word? 

In general :
- labeldoc **on** : word weight
- labeldoc **off** : global weight

In particular, regarding your propositions :
1. trainMode 1 : you can't have both weights at the same time
2. negative sampling : when there is a global weight (labeldoc off) the global weight is used, otherwise it s the weight of the picked negative samples which is used.

Does it make sense?

**Comment by ledw** [comment]
@pommedeterresautee thanks for the explanation. I think that makes sense. I'll change the case in labeldoc so we can handle sentence weight.

**Comment by ncammarata** [comment]
I just wanted to say that I had the same request, and was grateful to see this thoughtful discussion and execution.

**Comment by pommedeterresautee** [comment]
@ncammarata may I ask you what is your use case? It may give everybody ideas on how to leverage starspace representation

**Comment by ncammarata** [comment]
@pommedeterresautee I'm interested in using it for a network scenario. I want to be able to construct a graph of the system I'm working with, which in my case is connected operating systems with shared files, and arbitrarily make predictions within it. So I can say that X person looked at file Y for Z minutes, so what other files should I prioritize for their viewing.

Except I can basically choose any part of my graph to make these kinds of predictions. I haven't actually done any work with StarSpace on this yet, but that's my desired outcome, and I was happy to see weighted connections looking possible.

Does that make sense?

**Comment by ledw** [comment]
Closing the issue as weight importance is added.
